---
title: "An Epidemic in India"
date: "2018-01-17"
categories: []
slug: "an-epidemic-in-india"
---
## Prologue

A disease has spread throughout this great land of ours. To be sure, this disease is not new to us Indians. In some ways it has become part of our very national DNA. It has been with us for thousands of years. What harm then, one might ask, could such a familiar disease do to our nation and civilization if we have survived thousands of years with it? India today is not the India of old. India today is connected both within and without. Our formerly insular society is barraged with new cultural memes everyday. We must compete globally or risk being left behind. Many will argue that that is exactly what our "New India" is doing. But then, if we're doing everything right, why are we still on the second rung of ladder of nations? Why is our name hyphenated with Pakistan but never with China? Why are we, still, in the eyes of the world and also in fact, an "also ran"? There is one characteristic feature which distinguishes Indians from people of the nations we most wish to compete with. Ask any Indian traveler. Even the most "nationalist" amongst them will agree with this assertion. Indians - and by "Indians", I mean the upper class, upper caste, 5% " creamy layer" of our society - are a self entitled people, who cannot be bothered to clean up after themselves, lift their own luggage or display basic courtesy towards those who do the actual cleaning and lifting. This is the disease I'm referring to. It's called *entitlement*. I will give one illustrative example of this phenomenon.

## The Stuff Which Comes Between The Prologue and Epilogue

I was sitting in the food court of Terminal 2 of the Mumbai International Airport (CSIA), passing time, waiting for my flight's boarding time. It was hard to find a table to sit at, because most tables were dirty and littered with the leftovers of previous diners. Empty KFC boxes with chicken bones, pizza boxes with the uneaten crusts, and so on. As I sat there part me thought it would be easier to just get up and throw away all the trash than to wait for someone else to do it. But, I was preoccupied with my phone going through the latest developments on twitter. Eventually, I noticed a scrawny man in a cleaner's uniform moving towards the tables to clean them. "Good", I thought. "Finally. Someone's going to clean up this mess". Then I noticed another man, well dressed, obviously an air traveler with a great air of superiority around him, waving his finger at the cleaner, ordering him to clean the tables. Then it hit me, that the cleaner was being ordered around by this pompous looking gentleman. Now, there are few things which annoy me more than pompous assholes ordering someone to clean up the mess left behind by *other* pompous assholes. So, I got up, went to the nearest dirty table and started clearing it, chicken bones, pizza crusts and all. I figured if I couldn't change how my fellow Indians behave and how they treat others who do so much for them, the least I could do was to pitch in and give this weak, meek, tired looking man a helping hand. Now, I realise that having described the other air traveler as a "pompous asshole", it follows that I myself must be a humble saint. Or so the reader might think. I assure you I'm no such thing. I'm very far removed from saintliness or any kind. However, I do like to think, that at the very minimum, I'm a *decent* human. And that as a decent human, I should do the *decent* thing and not stand idly by when I see someone's dignity being stepped upon. That is, in fact, all we need. Just a *little* *bit* of decency. Just a *little bit* of respect for the work done day and night by the nameless millions who grow our food, drive our vehicles, bring us milk and clean our homes. It does not take a gigantic personal transformation to develop such an attitude in an individual. After all, you're not being asked to give up your cushy desk job and mow the fields, milk the cows or pick up the garbage every morning. You're not even being asked to become charitable towards the less fortunate, though it would certainly not hurt to do so. All that is being asked of you, and of me, is a *little bit of decency*. Just a smile and a nod for someone cleaning the toilets in that billion dollar airport or train station. Just a thank you for the driver who picks you up and drops you off. Just the smallest gestures of appreciation of the work that each person does, which makes your modern life of comforts a possibility, the same exact way, that *you* would want *your own work* to be appreciated by your superiors. And, yes, next time you eat in a self service area, don't wait for a cleaner to come along. Clean up after yourself. Take your tray and dump the leftovers in the bin. It's there. I assure you. You might have to look for it but it's there. It won't cost you any extra calories and you'll spread positivity around you. And if you don't find a bin then look for the nearest individual with a badge or a name tag and request them politely to install a garbage bin. Such a change in an individual's behaviour might seem like a very minor thing. But when you take many individuals, each of whom changes by just a little bit, the system as a whole can end up undergoing a dramatic transformation. That is the sort of transformation we need to make our nation more than a "also ran". And all it takes is just the tiniest bit of change in each individual's behaviour.

## Epilogue

As I walked away from the food court and towards my boarding area, I saw an old man, frail, likely suffering from arthritis and other ailments. He had been eating something and a tiny morsel - the size of a pea or less - had fallen on the shiny marble floor. There was no one watching him. He could have just let that grain of food lie on the floor and no one would have held a grudge against such an old man for not bending down for such a small piece of garbage. Nevertheless, with shaking knees and a body clearly in pain, he bent down to pick up that morsel to throw it in the garbage along with the rest of the leftovers in his hand. As he stood up our eyes met and I smiled. He smiled back and I felt a pang of joy run through me. All is not lost, I thought to myself. We can still beat this epidemic and come out better and stronger for it.