---
title: "Research Interests"
date: "2018-11-10"
slug: "research"
---
An abridged version of my research statement can be found here: [research-statement-abridged](/wp-content/uploads/2023/03/research-statement-abridged.pdf)

# Overview

My primary research interest lies in the field broadly referred to as *quantum gravity*. I did my graduate training at Pennsylvania State University, under Prof. Stephon Alexander and Prof. Martin Bojowald. My graduate work involved applying ideas from many-body phenomena to cosmology. In particular we explored whether a four-fermion attraction between fermions mediated by the gravitational connection could lead to the formation of a cosmological [fermionic condensate](http://arxiv.org/abs/hep-th/0609066). This work further led us to propose a [possible resolution](http://arxiv.org/abs/hep-th/0702064) to the cosmological constant problem. With my advisor and co-workers I also [explored](https://dx.doi.org/10.1088/1475-7516/2009/09/025) the possibility that the acceleration of the universe as induced from measuring supernovae redshifts and fitting with CMB data from the WMAP satellite could in fact be attributed to the possibility that our solar system is located in the interior of a cosmological void spanning $\sim$ 100-150 mega parsecs. While at Penn State I was also able to learn about *Loop Quantum Gravity*, which is considered the main competetitor to String Theory as a candidate theory of quantum gravity. With my collaborator Sundance Bilson-Thompson, I have written an introductory text on LQG, titled [*LQG for the Bewildered*](http://arxiv.org/abs/1402.3586), published in 2017 by Springer Nature. There is a common thread which runs through all my work - *the desire to understand how best to formulate a complete, consistent theory of quantum gravity*. For this purpose I have employed various tools from quantum information, many body physics and canonical quantum gravity. The shared motivation behind all of my work has been to understand how our smooth, classical spacetime arises from an underlying quantum substrate which might take the form of a tensor network or a Hubbard model on an abstract lattice. Of course, no theory of quantum gravity can be considered complete if it does not incorporate the particles of the standard model and their associated interactions. Therefore my work has also focused on trying to understand how elementary particles can be [embedded](http://arxiv.org/abs/1002.1462) within loop quantum gravity, a possible [relationship](http://arxiv.org/abs/1307.0096) between elementary particles and quantum computation, the emergence of non-abelian gauge fields from [defects](http://arxiv.org/abs/1309.0652) in spin-networks and, more recently, a possible [relationship](https://dx.doi.org/10.1140/epjc/s10052-022-10701-6) between scattering of elementary particles and semiclassical states of geometry. Over the years I have realised that *the insights we have obtained from research in String Theory, such as the fundamental significance of conformal field theories, the AdS/CFT correspondence and the existence of various dualities (T, S and R dualities for example) will ultimately be core ingredients of any theory of quantum gravity*. Therefore I have undertaken self study of this subject and even attempted to draw [connections](http://arxiv.org/abs/1711.05693) between String Theory and LQG. At the same time I firmly believe that the insights gained from LQG, such as importance of viewing gravity as a theory of connections rather than a metric, the quantization of area and volume operators and the description of the LQG state space in terms of *spin networks* will also be essential ingredients of any ultimate theory of quantum gravity. The large volume of work coming from the Strings community on the topics of tensor networks and quantum information over the past decade only serves to support this perspective. In the future I intend to continue to pursue the various threads coming from these allegedly divergent fields in an attempt to find reconciliation between the two.

# History and Motivation

The problem of quantum gravity is *the* outstanding problem of our generation. Since as long as I can remember I have wanted to work on this grand project of unification of all forces and interactions. Now, as a theoretical physicist I actually have the privilege of participating in some small way in solving this awesome puzzle. When I applied to graduate schools at the end of my BSc in 2003 it would have been natural and expected for anybody to choose to study String Theory. I was as yet unaware of the controversies regarding the subject which have arisen over the past two decades, and works by authors, such as Peter Woit and Lee Smolin, critical of the stringy paradigm had yet to be written. I happened to chance upon some link or paper which introduced me to an alternative. This was the theory known as Loop Quantum Gravity (LQG), which over the past two decades has made great enough strides that now respectable string theorists are willing to organize conferences ([Quantum Gravity 2020](https://www2.perimeterinstitute.ca/conferences/quantum-gravity-2020) and the upcoming [Quantum Gravity 2023](https://indico.imapp.ru.nl/event/106/)) with LQG researchers. What captured my attention twenty years ago was the fact that LQG claimed to have understood how to quantize geometry itself. The idea that spacetime itself should be a quantum mechanical construct, rather than a preexisting, infinitely smooth continuum as was the case in classical mechanics and quantum field theory, held deep intuitive meaning for me. I felt motivated strongly enough to drive some eight hundred miles from Rolla, Missouri to Penn State in my 1992 Toyota Camry in order to meet one of the leading lights of the field - Prof Abhay Ashtekar. Our meeting was brief and awkward. I was young and knew next to nothing about the subject. I only had my intuition and my ambition to show. Abhay was cordial as he always is, but apart from polite generalities our conversation did not go much further. Returning from my road trip I knew that I would definitely be applying to Penn State for a PhD position. I ended up applying to four places. Harvard, Washington University (St. Louis), UT Austin and Penn State. I was accepted at all of them except Harvard. That one was a long shot anyways. Ultimately I went with my gut feeling and chose Penn State. Now some twenty years and many rejected papers later one might think that I regret my choice of LQG over String Theory. I do not. This has led me to study the AdS/CFT correspondence, quantum computation and quantum error correction, tensor networks and many body physics as evidenced by my list of papers. Below I go into greater detail about the particulars of each one of my research projects.

# Recent Work

At present I am working on the following different projects, which are at various stages of completion:

1.  **Origin of Arrow of Time from Symmetry Breaking in Spin-Networks**: this work relies on the recognition that the tensor network state formalism used to describe many-body quantum states is essentially identical to the spin-networks which are the building blocks of spacetime in LQG. Using techniques developed for tensor networks, which allow one to make time-reversal symmetry into a local gauge symmetry, we can hope to ask and answer the question of whether the same can be done for spin-networks. If so, then the possibility arises that symmetry breaking of this *local* time-reversal gauge field can give rise to a macroscopic cosmological arrow of time. A preliminary version of this work was presented at the workshop [EVONET18](https://www.pks.mpg.de/evonet18/) on tensor network held at Max Planck Institute in Dresden in June 2018. The manuscript for this work is in the final stages of completion.

2.  **Coherent State and Particle Scattering in Loop Quantum Gravity**: One cannot have a theory of quantum gravity if it does not include matter. For many researchers the apparent lack of matter degrees of freedom and their interactions is one of the principle drawbacks of LQG. However, in [10.1140/epjc/s10052-022-10701-6](https://dx.doi.org/10.1140/epjc/s10052-022-10701-6) (also available at [arXiv:2208.10632](https://arxiv.org/abs/2208.10632)) with my former masters student Devadharsini Suresh I have shown that there exists a natural interpretation of the degrees of freedom living on the edges of spin network degrees as particles with definite momenta. This interpretation requires that we work with coherent states (known as *coherent intertwiners*) which represent a classical geometry. In a way this is very satisfying. It tells us that only when a classical spacetime emerges from the underlying quantum substrate does the idea of particle excitations with definite momenta begin to have concrete meaning. The concept of momentum itself is associated with symmetries of a smooth background spacetime as we have learned from QFT and the description of symmetries of flat space in terms of the Poincare group. There is also a natural connection between our approach and the Complexity=Volume proposals of Susskind and collaborators made in the context of eternal black holes in AdS/CFT over the past several years.

3.  **Quantum Error Correction in Loop Quantum Gravity**: Over the past few years, work by Preskill, Almhieri, Pastawski and others has emphasized the role played by quantum error correction in reconstructing the bulk geometry of an asymptotically AdS spacetime from the boundary conformal field theory. Recently I have recognized the close relationship between a topological model for elementary particles - first introduced by Sundance Bilson-Thompson in 2005 - with a three qubit quantum error correcting code. These topological excitations find a natural embedding within the spin network picture of spacetime coming from loop quantum gravity. I presented this work in a talk at the Loops' 19 conference at Penn State in June 2019. The resulting paper can be found here [arXiv:1912.11725](https://arxiv.org/abs/1912.11725).

4.  **Connecting LQG and String Theory via Quantum Geometry**: In [arXiv:1711.05693](http://arxiv.org/abs/1711.05693) I have argued that the Nambu-Goto action of the bosonic string theory should be viewed as arising from the expectation value of the LQG area operator acting on an ensemble of spin-networks. This work represents one of the rst pieces of evidence for a direct relationship between String Theory and Loop Quantum Gravity. This work was presented in a talk at the 6th Tux workshop on Quantum Gravity in Feb 2018.

5.  **Phases and Thermodynamic Geometry of Anti-deSitter Black Holes**: Alongwith my students and collaborators I have investigated the thermodynamic behavior of black holes in anti-deSitter spacetime. One aspect is the relationship between the horizon physics as described by the Damour-Navier-Stokes equation and phase transitions in the bulk as described by the black hole Van der Waal type equation of state.

6.  **Identifying Phases of Spin-Networks via Deep Learning**: Deep learning has become a standard tool in the study of complex physical systems, in particular the analysis of phases of many-body quantum systems. With my student I am in the process of understanding how to apply deep learning techniques - in particular, the Restricted Boltzmann Machine (RBM) formulation - to understand phases of spin-networks in LQG.

7.  **2$^{\textrm{nd}}$ Edition of "*LQG for the Bewildered"***: With my collaborator Sundance Bilson-Thompson, I have authored an introductory text on Loop Quantum Gravity. The success of the first edition has led the editor to request us to prepare a second edition. We are currently in the process of editing, revising and expanding the contents of the first edition for this purpose.

# Future work

Below I list some goals I hope to accomplish over the next several years. These include:

1.  ***To concretely establish the relationship between LQG and String Theory***: My paper [arXiv:1711.05693](http://arxiv.org/abs/1711.05693) was only an initial attempt at connecting these two fields. Much more work is required to understand how the discrete structure of geometry in LQG will affect the corresponding stringy model. In a discrete background, the conformal symmetry of the string worldsheet will necessary be broken. This might provide an avenue to construct loop-string solutions which correspond to four-dimensional spacetime without the need for compactifications, supersymmetry or anthropic reasoning.

2.  ***Experimental signatures of quantum gravity***: The upgraded LHC presents a novel opportunity for searching for signatures of quantum gravity. One possibility that I have suggested in [arXiv:1208.3335](http://arxiv.org/abs/1208.3335) is that at or near the Planck scale the local symmetry group of spacetime will become $SL(2,\mathbb{Z})$rather than$SL(2,\mathbb{C})$. This change should manifest itself in the form of gaps or steps in the spectra of particles produced in hadron collisions. A natural question is why should the Planck scale $~ 10^{16}$TeV be accessible at the LHC. As argued by me ^[1](#fn-639-1 "Read footnote.")^, and also in prior work by Xavier Calmet and collaborators, a proper analysis of the running of Newton's constant strongly suggests that the *real* Planck scale will be much lower than its naive value of$~ 10^{16}$ TeV.

3.  ***LQG, Holography and Quantum Computation***: In one of my earlier papers ([arXiv:1307.0096](http://arxiv.org/abs/1307.0096)) I suggested a correspondence between particles of the standard model and unitary gates required for universal quantum computation. Since then several works by Preskill, Pastawski and collaborators relating quantum error correction to the question of determining the bulk/boundary correspondence in AdS/CFT have made the initial motivation behind my work appear much less speculative. I want to continue this earlier work and over time provide a more concrete mathematical foundation for this proposed correspondence between the standard model and quantum computation.

4.  ***Quantum Gravity and Tensor Category theory***: Broadly speaking my work has focused on trying to understand the form a theory of quantum gravity might ultimately take. While there is progress on many different fronts in understanding *aspects* of quantum gravity, there is as yet no concrete mathematical formulation for the theory. In order to construct such a formulation one would first need to identify the appropriate mathematical framework in which to pose the problem. Recently I have been led to the belief that tensor category theory provides the appropriate tools to pose the problem and also to write down a candidate system of equations for quantum gravity. This work is in its infancy as I am still learning category theory. However, I strongly feel that this is the correct framework for asking and answering such questions.

------------------------------------------------------------------------

1.  ::: {#fn-639-1}
    See my [blog post](https://www.quantumofgravity.com/blog/2018/10/30/the-planck-scale-may-be-closer-than-it-appears/) "*The Planck Scale May Be Closer Than It Appears*" quantumofgravity.com 
    :::