---
title: "Competitive Nationalism and (the myth of) Islamic Homogeneity"
date: "2018-01-11"
categories: []
slug: "competitive-nationalism-and-the-myth-of-islamic-homogeneity"
---
Recently the Chief Minister of Karnataka, Mr. Siddharamaiah, made the following observation on twitter regarding the recent communally motivated murders in the Dakshin Kannada (South Karnataka) district. Expressing grief as the deaths of both victims from different communities, he described the tragic incidents as the results of "competitive fanaticism" between extremists on either side This expression, "competitive fanaticism", perfectly summarizes the favored tactic of certain elements of India's polity. The goal is too keep the embers of nationalism and religious identity burning just hot enough to maintain a state of constant dread in the general public, but not so hot that the fire gets out of hand and burns down the whole village. Of course, it is impossible to control the evolution of a system as complex as human society, no matter how resourceful any individual or group of individuals might be. One nevers knows when the fire might burn just hot enough in one place at one time and set the whole system on flames. That is why it is important for leaders of good faith to soothe the upset nerves of people who are innocent victims of such competitive fanaticism, in addition to taking all possible steps using the state's machinery to tamp down on extremist elements of any hue. Consider this. A Muslim from Maharashtra and a muslim from Bengal in the same room. How difficult or easy would it be for a general observer to realize that the two don't come from the same cultural backgrounds? Not difficult at all, right? Even if both have facial hair and are wearing skull caps or other items identifiable as being of Muslim origin, that won't mask the differences in speech, attitude, dietary preference, clothing habits and other cultural traits, between the two. So the obvious answer is "no, it would not be difficult at all to distinguish the different regional origins of the muslims"! Now imagine that instead of two Muslims in that room, we have two Hindus, one from Kerala and another from Gujarat. What would be answer to the question in this case? In this case, the question would not even arise, because it is \*\*understood\*\* that Hindus are a not a monolithic homogenous culture and that is great diversity within the people of the subcontinent who identify themselves as being "Hindu". It should also be \*\*understood\*\* that Indians Muslims are also not a homogenous entity. There is as much (or as little) difference in the thinking, behavior, speech, appearance and overall cultural identify of Muslims from Karnataka and Bihar as would be found between any two Hindus from the same states. However, the competitive fanaticism which is prevalent in today's politics is based in the fundamentally incorrect premise that Indian Muslims are a homogenous entity all sharing the exact same traits. This is, of course, a complete and malicious lie, whose purpose is to simply make the demonization of Muslims that much more convenient. After all, it is very easy to direct feelings of hate towards a single, undifferentiated entity, than to hate a vast and diverse population composed of many subcultures and tribes. Thus in order to fight those who seek to poison social discourse and sow communal hatred, it important to do three things. First, to reach out with humility, compassion and empathy towards \*\*all\*\* who are affected by communal violence. Second, to take all possible legal steps to counter those who wish to spread communal propaganda and hate speech. And, third and most importantly, we must celebrate and propagate at every available opportunity the diversity of thoughts, lifestyles and cultures which exist amongst all religions, communities and regions in this vast land of India.