---
title: "Multiverse, multiverse, where art thou?"
date: "2014-05-12"
categories: []
slug: "multiverse-multiverse-where-art-thou"
---
As I understand it, the multiverse concept arises as a consequence of the standard inflationary scenario which involves one or more scalar fields "rolling down" the side of a potential hill, causing an exponential increase in the "size" of the Universe soon after the Big Bang. Now the form of the potential itself varies from place to place. Though what "place to place" means, when you are talking about the time when the geometric exoskeleton of the Universe is still in the process of formation, is quite unclear to me. And because the potential varies from "place to place", different regions of spacetime inflate at different rates and generically many such exponentially inflating volumes are generated from an original patch of spacetime. This is the origin of the concept of a multiverse. The **basic assumption** behind all these scenarios is that the process of growth of geometry can be correctly modeled by the inflaton-potential scenario. And this is also the Achilles heel of the multiverse paradigm. What if the inflaton-potential scenario is only an effective description of the quantum processes which lead to the formation of geometric structure? That this is the case is clear if you have come to terms with the notion that "quantum geometry" underlies "classical geometry" and things such as metric, scalar fields and potentials arise from something more primitive. The resulting picture of spacetime is that of a fluid, which emerges from the interaction of its microscopic "atomic" constituents the same way the fluid (continuous) nature of water is the result of the interactions between many many discrete $H_2 O$ molecules. In this picture, there are no such things as "fundamental" scalar fields. What appears to be a "fundamental" scalar field is instead an order parameter describing the collective behavior of some underlying (non-scalar) degrees of freedom. Now just as the process of condensation, where water vapor turns into water, corresponds to a phase transition, the quantum geometric picture suggests that the classical continous spacetime arises due to condensation of a gas of some sort of "atoms of geometry". Such a process should be described in the language of many-body physics in terms of a transition from one phase of geometry to another. See Sabine's blog for her take on this. Also see my previous papers which talk about such a phase transition. Anyways, if this *is* indeed the real picture, then the "multiverse" is simply a consequence of taking an effective description of quantum geometry far too seriously and ignoring the fact that there is a more fundamental underlying dynamics that has to be taken into account. Of course there is no reason, a priori, for ruling out that the phase transition results in the formation of "domains", where each domain describes a slightly different classical geometry in a manner similar to the formation of domains in ferromagnetism. However, there is also no reason to why these domains would correspond to separate disconnected universes, rather than one universe divided into many regions with different geometric configurations. Whether or not these domains would correspond to the size of the observable Hubble volume today depends on the details of the underlying theory. Regardless of the details, one can see that a phase transition is a finite process in time. Once it has occurred and the new phase of geometry has emerged the resulting domains will not undergo exponential expansion because, after all, the "exponential expansion" was the phase transition itself! In short, from this perspective the "Multiverse" is a mirage, a result of sloppy reasoning which ignores the true dynamics of geometry. There is much more to be said, but this seems enough for now!