---
title: "Social Relevance of Quantum Gravity"
date: "2018-11-17"
categories: []
slug: "social-relevance-of-quantum-gravity"
---
Other ^[1](#fn-671-Motivation)^ than all the other very good theoretical reasons for wanting a theory of quantum gravity, there are some very good *practical* reasons for wanting such a theory. Ultimately the fate of scientists, theorists and experimentalists alike, rests in the hands of the general public and its elected or appointed political representatives. Why, after all, should the taxpayers fund so called "[blue skies research](https://en.wikipedia.org/wiki/Blue_skies_research)" and pay for all these theorists romping around the world, making merry in exotic locations and seemingly doing nothing of immediate social value? Couldn't all that money instead be put into building highways, hospitals and schools? And, of all the possible purely theoretical research avenues why should the public fund the one known as *quantum gravity* - a chimera that seems to have evaded theorists for almost sixty years now? It is the purpose of this post to convince skeptical readers that funding such an enterprise is not only *not* misguided but is of *central importance* for those societies who wish to compete and survive in the coming decades and centuries. No elaboration is needed regarding the central role that the storage and transmission of energy is its many forms - coal, oil, nuclear, wind, solar, fission, fusion - plays in our daily lives. However, what is often forgotten is the important role played by "blue sky research" conducted over the past several centuries in establishing the modern day technological framework for energy storage and transmission. The work of Ampere, Faraday and Maxwell was not motivated by any possible immediate technological applications. In the middle of the 19^th^ ^[2](#fn-671-Superscripts)^ century what immediate, social justification could Faraday have provided for researching the "lines of force" concept which later developed into the idea of field theory? Boltzmann, Clausius, Joule and Thompson's work on thermodynamics was also "blue sky research". Steam engines had been in existence since the 18^th^ century. Railroads and steam-powered barges were becoming the engines of trade and commerce in Europe and America by the time of Joule's work on the equivalence of mechanical and thermal notions of heat. However, without the concrete foundation provided by the laws of electrodynamics and the laws of thermodynamics, industrial progress would have been slow and fitful at best. Today we are on the threshold of a nanotechnological revolution where molecular machines and motors will be employed in every field, whether that be making self-healing paints and surfaces, targeted delivery of medicines to specific cells in the body, catalysis of chemical processes or safe degradation of hazardous biological and nuclear waste material. Once again, it is the theoretical work in the field of quantum thermodynamics and non-equilibrium processes done through the last decades of the 20^th^ century which will underpin this upcoming revolution. Another revolution, happening as I write this, is that in quantum computation. Ten, twenty, even hundred qubit systems have been designed and being used by companies such as Rigetti, IBM, Google and D-Wave Systems. One can even sign up for a limited amount of free computational time on these quantum computers! Quantum mechanics and entanglement were developed almost ninety years ago. But, it is only now that the full potential of quantum theory for technological development is coming to fruition. In ten years time, or perhaps sooner, commercial quantum computing systems should start becoming commonplace and in another twenty years this technology will likely reach our living rooms. Given these very real past and present developments, it would therefore hardly be any surprise, if "blue sky research" into a theory of quantum gravity were to yield massive social and technological dividends twenty, fifty or a hundred years from now. But, the seeds must be planted *now* if we expect our future generations to be able to harvest the fruits of our efforts. And, only a suitably informed and enlightened public and polity can provide the necessary fertile breeding grounds for new ideas and breakthroughs in quantum gravity.

------------------------------------------------------------------------

1.  [This post was motivated in part by a post on [Backreaction](https://backreaction.blogspot.com/2018/11/book-review-rigor-mortis-by-richard.html) and the associated comments thread. ]{#fn-671-Motivation}
2.  [Interestingly, markdown - or at least flavor running used by Jetpack at the moment - does not support superscript `^...^` and subscript `_..._` notation. So we have to resort to using HTML tags `<sup>` and `</sup>` for the time being. For e.g. `19<sup>th</sup>` renders as 19^th^ ]{#fn-671-Superscripts}