---
title: "Elementary particles and quantum geometry"
date: "2013-01-26"
categories: []
slug: "elementary-particles-and-quantum-geometry"
---
Black holes are formed due to the gravitational collapse of matter - ordinary matter, consisting of the particles and excitations of the Standard Model that we know and love. These include electrons, photons, neutrinos, quarks, mesons etc, and their respective anti-particles. General Relativity tells us that the properties of (macroscopic) black holes are universal, in that they do not depend on the precise fraction of each particle species in the initial "mixture". A black hole formed from the collapse of a non-rotating cloud of $n$electrons and$n$positrons will be neutral, non-rotating and of mass$2n m_e$, where $m_e$is the electron mass. Let us refer to this black hole as$bh(n,e^-; n,e^+)$or$bh_e$for short. A black hole formed from the collapse of cloud of$m$neutrinos and$m$anti-neutrinos, where$m * m_{\nu} = n * m_e$ ($m_{\nu}$being the mass of a neutrino). According to our labeling scheme, this black hole will be labeled as$bh(m,\nu;m,\bar\nu)$or$bh_{\nu}$for short. Both black holes have the same mass$M = n * m_e = m * m_{\mu}$and thus the same horizon area$A = GM/c^2$. For an external observer $O$who happens upon$bh_e$and$bh_{\nu}$, after the gravitational collapse process has completed and the black holes have reached equilibrium, the two objects will be indistinguishable (as long as $n, m \gg 1$so that the black hole can be treated semiclassically):$bh_e \equiv bh_{\nu}$. Such an observer will be unable to tell, by any probes or experiments, which black hole formed from the electron-positron mixture and which one formed from the neutrino-anti-neutrino mixture. $O$will see both objects as identical uncharged, non-rotating black holes with horizon area$A$and mass$M$. In the LQG inspired picture of quantum gravity, the microscopic degrees of freedom of an uncharged, non-rotating black hole of the type considered above, are given by the punctures on its horizon which endow the black hole with area. Each puncture contributes a quantum of area. We also know that the mass of the black hole is proportional to its area. Thus, when such a black hole emits or absorbs a quantum of energy - in the form of some particle of mass $m'$- its mass, and therefore its area, decreases by a fixed amount. Similarly when a quantum is absorbed the mass and the area increase by the same fixed amount. Now, imagine that$bh_1$emits a particle which is then absorbed by$bh_2$. The area of $bh_1$decreases by some amount$\delta A$and the area of$bh_2$increases by the same amount. What happens to that quantum of area after its emission by$bh_1$and before its absorption by$bh_2$? It is clear that the area quantum is transported by the particle in question. We can then get rid of the two black holes and we are still left with a single, massive elementary particle to which we can associate a quantum of area. This reasoning should apply to *all* (massive) excitations be they electrons, protons, quarks, mesons or neutrinos. We shall return to the question of what happens with *massless* particles - such as photons - a bit later. As far as elementary particles such as electrons and neutrinos are concerned we like to imagine that we know everything there is to know about their degrees of freedom which are the particle's mass ($m$), spin ($j$) and charge ($q$). In general, $q$ can include magnetic, color and other charges, in addition to the usual Coulomb electric charge. If there were to exist any other "hidden" degrees of freedom of an elementary particle, which we have not yet encountered in experimental searches, then that would seem to call into question the entire framework of the standard model. Thus, simplicity and consistency with pre-existing experimentally verified models, demands that the area quantum associated with an elementary particle must somehow be encoded in its mass, spin and charge quantum numbers!