---
title: "Theoretical Physicists in India"
date: "2018-01-13"
categories: []
slug: "theoretical-physicists-in-india"
---
There are many research centers and researchers in India working in hep-th (High Energy Physics, Theory), gr-qc (General Relativity/Quantum Cosmology) and quant-ph (Quantum Physics). However they are scattered all over the place and I have not been able to find a place which lists the names of places and individuals working in these fields in India. So, I figured, why not make a list! Here is my attempt at making one. It is, hopefully, a continuing work to be expanded over time. Naturally, this list reflects my own intellectual biases and is not meant to be a comprehensive list of all researchers in theoretical physics in India.

  ----------------------------------------------------------------------------------------------------------------------------------------------------- ------------------------------------------------------------------------------------- ---------------------------------------------------------------------------------- ---------------------------------------------------------------------------------------------------------------------------------------------------
  **Name**                                                                                                                                              **Institution**                                                                       **Areas of Interest**                                                              **Publications**

  **[Thanu Padmanabhan](http://www.iucaa.ernet.in/~paddy/)**                                                                                            [IUCAA](http://iucaa.in), Pune                                                        Classical General Relativity, Cosmology, Emergent Gravity, Quantum Gravity         [INSPIRE](https://inspirehep.net/search?ln=en&ln=en&p=exactauthor%3At.padmanabhan&of=hb&action_search=Search&sf=earliestdate&so=d&rm=&rg=50&sc=0)

  [**Romesh Kaul**](https://www.imsc.res.in/users/kaul)\                                                                                                [IMSc](https://www.imsc.res.in/) Chennai, [CTP](http://www.ctp-jamia.res.in/) Delhi   Black Hole Entropy, Loop Quantum Gravity, Knot Invariants, Mathematical Physics\   [INSPIRE](https://inspirehep.net/search?p=exactauthor%3ARomesh.K.Kaul.1&sf=earliestdate)

  **[Dharam Vir Ahluwalia](https://www.researchgate.net/profile/Dharam_Ahluwalia)**                                                                     IIT Guwahati, IUCAA, Himachal Pradesh Univ\                                           Standard Model and Beyond, Neutrino Physics, Dark Matter                           [INSPIRE](https://inspirehep.net/search?p=exactauthor%3AD.V.Ahluwalia.1&sf=earliestdate)

  **Kinjalk Lochan**                                                                                                                                    IISER Mohali                                                                          Quantum Foundations, Black Holes, Cosmology, Quantum Gravity                       [arXiv](https://arxiv.org/search/?query=Lochan%2C+Kinjalk&searchtype=author&abstracts=show&order=-announced_date_first&size=50)

  [**Golam Mortuza Hossain**](http://www.iiserkol.ac.in/~ghossain/)                                                                                     [IISER](http://www.iiserkol.ac.in/~ghossain/), Kolkata                                Loop Quantum Gravity, Quantum Field Theory, Black Hole Entropy, Cosmology          [INSPIRE](https://inspirehep.net/search?p=exactauthor%3AG.M.Hossain.1&sf=earliestdate)

  **[Sushant G. Ghosh](http://www.ctp-jamia.res.in/people/sghosh.html)**                                                                                [CTP](http://www.ctp-jamia.res.in), Delhi                                             Black Holes, Classical General Relativity, Gravitational Collapse                  [INSPIRE](https://inspirehep.net/search?ln=en&ln=en&p=exactauthor%3AS.G.Ghosh.1&of=hb&action_search=Search&sf=earliestdate&so=d&rm=&rg=250&sc=0)

  [**Ghanshyam Date**](http://www.imsc.res.in/~shyam)                                                                                                   [IMSc](http://www.imsc.res.in/~shyam), Chennai                                        Loop Quantum Gravity, Gravitational Waves, High Energy Theory,                     [INSPIRE](https://inspirehep.net/search?p=exactauthor%3AG.Date.1&sf=earliestdate)

  **[Arun K. Pati](http://www.hri.res.in/~akpati/)**                                                                                                    [QIC Group](http://www.hri.res.in/~qic/), [HRI](http://www.hri.res.in/), Allahabad    Quantum Information, Quantum Computation, Geometric Phases                         [INSPIRE](https://inspirehep.net/search?p=exactauthor%3AA.K.Pati.1&sf=earliestdate)

  [**Rathin Adhikari**](http://www.ctp-jamia.res.in/people/rathin.html)                                                                                 [CTP](http://www.ctp-jamia.res.in/), Delhi                                            Standard Model Phenomenology, Baryogenesis, Cosmology, Supersymmetry               [INSPIRE](https://inspirehep.net/search?ln=en&ln=en&p=exactauthor%3AR.Adhikari.2&of=hb&action_search=Search&sf=earliestdate&so=d&rm=&rg=50&sc=0)

  **[Hemwati Nandan](https://scholar.google.co.in/citations?user=c_Mg0gQAAAAJ&hl=en)**                                                                  [Gurkul Kangri University](http://www.gkv.ac.in/), Haridwar                           QCD, Classical General Relativity, Cosmology,                                      [INSPIRE](https://inspirehep.net/search?p=exactauthor%3AH.Nandan.1&sf=earliestdate)

  **[Loganayagam R.](https://www.icts.res.in/people/loganayagam)**                                                                                      [ICTS](https://www.icts.res.in/), Bengaluru                                           String Theory, Black Holes, Quantum Field Theory                                   [INSPIRE](http://inspirehep.net/search?p=author%3AR.Loganayagam.1+)

  **[Kamal Lochan Panigrahi](http://iitkgp.ac.in/department/PH/faculty/ph-panigrahi)**                                                                  IIT Kharagpur                                                                         String Theory, Quantum Gravity, High Energy Theory                                 [INSPIRE](https://inspirehep.net/search?p=exactauthor%3AK.L.Panigrahi.1&sf=earliestdate)

  **[Kazuyuki Furuuchi](https://manipal.edu/mu/academics/centers-of-excellence/mcns-manipal/department-faculty/faculty-list/kazuyuki-furuuchi.html)**   Manipal Center for Natural Sciences                                                   Cosmology, Elementary Particles, String Theory                                     [INSPIRE](https://inspirehep.net/search?p=exactauthor%3AK.Furuuchi.2&sf=earliestdate)

  **[Amitabh Virmani](https://www.iopb.res.in/members/virmani)**                                                                                        Institute of Physics, Bhubaneswar                                                     String Theory, Black Holes, Mathematical Physics                                   [INSPIRE](https://inspirehep.net/search?p=exactauthor%3AA.Virmani.1&sf=earliestdate)
  ----------------------------------------------------------------------------------------------------------------------------------------------------- ------------------------------------------------------------------------------------- ---------------------------------------------------------------------------------- ---------------------------------------------------------------------------------------------------------------------------------------------------