---
title: "``Loop Quantum Gravity is Dead ... ''"
date: "2020-06-23"
categories: []
slug: "the-death-of-loop-quantum-gravity"
---
\... is a phrase that many high energy theorists, especially those of the stringy persuasion, long to hear. Fortunately, to borrow a phrase from Mark Twain, reports of the death of loop quantum gravity (LQG) are greatly exaggerated. Premature declarations of the imminent demise of LQG have a long history. The most recent one comes from a recent [article](https://www.quantamagazine.org/black-hole-paradoxes-reveal-a-fundamental-link-between-energy-and-order-20200528/) in Quanta magazine:

> > > Santos noted that "the only theory out there" that unifies the fundamental forces in a single framework is string theory. Rival approaches such as loop quantum gravity attempt to quantize gravity by dividing space-time into pieces, without connecting gravity with the other forces. **"If the weak gravity conjecture is correct, things like loop quantum gravity are dead,"** said Santos. [emph mine]

[Santos](https://www.damtp.cam.ac.uk/person/jss55) follows in the footsteps of a long line of illustrious predecessors who have, at various points and for various reasons, declared LQG either dead or dying. I list a few of these here. Lubos Motl on his [blog post](https://motls.blogspot.com/2006/01/pure-quantum-gravity-cannot-work.html) on the weak gravity conjecture states:

> > > \... pure theories of quantum gravity cannot work. This conclusion \... applies to various loop quantum gravities, spin foams, causal and acausal, dynamical and non-dynamical triangulations, tetrahedronizations, and any other misinterpretations of quantum gravity that you have heard of.

't Hooft in [@t-Hooft2017Natures] says:

> > > \... there [has] been an abundance of completely wild concoctions [for theories of quantum gravity] that serious researchers have come up with. Lack of phantasy is not our problem [9][10][11]

where the papers he cites as examples of "wild concoctions" include Sorkin's causal set theory [@Sorkin2003Causal], Rovelli's 1997 review of LQG [@Rovelli1998Loop] and an review of causal dynamical triangulations (CDT) [@Ambjorn2014Quantum]. To be fair to 't Hooft, in the same paper he also expresses his long standing skepticism about string theory:

> > > \... String theory was an interesting guess, but may well have been a too wild one.

Of course, there have been no dearth of similar declarations for string theory also. The most famous one was likely said by Stephen Hawking in 1979. Referring to the fact that $N=8$supergravity (Where$N$refers to the number of supersymmetric charges in the theory.) in 10 dimensions was a unitary and renormalizable theory Hawking apparently stated at a conference something along the lines of "Physics is over". He said as much in a Physics Today article in 1981 [@Hawking1981Is-the-End-in-Sight] titled "Is the End in Sight for Theoretical Physics?" Of course, the implied conclusion is that String Theory, which was yet to cured of its troublesome anomalies in the so-called first superstring revolution of 1985, was also a dead, or even worse, an irrelevant theory. More recently there has been there has been critical tome titled "Note Even Wrong" by Peter Woit [@Woit2006Not-Even]. The title is chosen for devastating effect to suggest that string theory, far from being right, is "not even wrong" in that it provides no falsifiable predictions which might be observable in any near or medium term (10-50 years) experiments. Of course, the lack of falsifiable predictions does not prove that none of the physical insights gained from string theory, such as the various dualities relating large and small scales and relating theories with large and small couplings, are going to be found to be relevant for whatever form a correct, consistent theory of quantum gravity might take in the future. On the contrary, any final theory of quantum gravity will contain many of the ingredients discovered by string theorists such as the existence of non-perturbative extended objects such as one dimensional strings and higher dimensional branes. The most important of these ingredients is the statement of holography(also known as the AdS-CFT correspondence or the Maldacena conjecture.) - that physics of a gravity theory in a$D+1$dimensional anti de-Sitter (AdS) spacetime can be mapped to the physics of a$D$ dimensional conformal field theory living on the boundary of that spacetime. The important lesson is that string theory has gone through a great many ups and downs during its long history. In fact, the situation has now reached a stage that what used to be known as the "string landscape" is now referred to as the "string swampland" and there is an entire industry of research into "swampland" physics built around this concept. I wonder how many further stages of devolution will have to occur, from landscape to swampland to festering pits of doom, before string theorists try to adopt a more pragmatic and less dogmatic approach to quantum gravity research. The irony of the situation can be seen in this [video](https://www.youtube.com/watch?v=VZbtV-bilu0) of a "Vision discussion" held at the end of the most recent Strings conference. Near the beginning of this discussion Daniel Harlow feels the need to state that "I think string theory is **still** a good candidate for quantum gravity"! During the rest of the discussion one would be hard pressed to find any actual references to string theory! Similarly, it is highly premature to declare LQG to be "dead" based on the possibility that the weak gravity conjecture might be correct. The physical insights which have been gained from LQG research, such as the quantization of geometric operators and the construction of a spin network basis for the Hilbert space of quantum geometry, are very much likely to be part of the ultimate quantum gravity theory. In fact, a lot of what passes as "string theory" research these days is actually work done in the context of so-called "tensor networks" applied to the AdS-CFT correspondence. And, unsurprisingly enough for those not inclined towards partisan politics such as myself, tensor networks *are nothing more than the spin networks of LQG*!(At this point one might ask how is this the case, to which I would reply "spin networks and tensor networks are the same thing in the same way as a red ball and a blue ball are both balls"! Further details to appear in a not too distant blog post or arXiv paper.) Of course, string theorists would be loath to admit the bitter fact that one of their primary successes, and one which comes closest to providing some sort of falsifiable predictions, ends up relying on precisely the same elementary building blocks discovered more than 30 years ago by theorists working on something known as loop quantum gravity! The weak gravity conjecture may very well be correct. There have been several recent claimed proofs in the literature [@Cheung2014Naturalness; @Cheung2018Proof; @Hamada2019Weak]. However, all of these are based on arguments involving quantum field theory and string theory. What makes the most persuasive argument in favour of the WGC, in my humble opinion, is a paper by Shahar Hod [@Hod2017A-Proof]. He shows, using arguments based on the relaxation times of the quasinormal modes of near-extremal Reissner-Nordstrom black holes, that the WGC must hold if a certain other conjecture (also framed and proved for several particular cases by Hod) regarding the "universal relaxation bound" for a thermodynamic system is true. This argument does not require any knowledge of the UV field theory and makes no assumptions about the nature of the quantum gravity theory. These facts are what make Hod's proof particularly compelling in my view. Given the preponderance of evidence in favour of the WGC, is it correct to conclude that LQG is "dead"? The answer to that is a resounding "no". On the contrary, this fact now throws up a challenge to the LQG community, who have thus far ignored the physics of charged extremal black holes for the most part, to explore that region of the theory space and to inquire what new insights the correctness of the WGC implies for the structure of LQG. The path towards this understanding, in my opinion, lies in understanding how to model the quantum geometry of charged AdS black holes along the lines discussed in one of my [previous blog posts](https://www.quantumofgravity.com/blog/2019/08/25/specific-heats-of-ads-black-holes-and-quantum-geometry/).