---
title: "The \"Rediscovery\" of Spin Networks and Loop Quantum Gravity"
date: "2024-02-10"
categories: []
slug: "the-rediscovery-of-spin-networks-and-loop-quantum-gravity"
---
Its hard to describe the frustration and anger I feel to see all these papers talk about "tensor networks" and geometry as if they are discovering something new which wasn't already discovered 31 years ago under the framework known as Loop Quantum Gravity (LQG). Take this recent paper for example: http://arxiv.org/abs/2402.05910 "First, how might we make a tensor network without a rigid, fixed background? As a first guess, we might imagine a model in which we consider more than just one tensor network, allowing (somehow) for a "superposition of tensor networks", each with a different geometry. This is a decent first step towards modeling gravity." Yes. Indeed. It would be a decent first step towards modeling gravity. Only thing is this "first step" was taken several decades ago when \@carlorovelli, Smolin, Baez, Krasnov, Ashtekar and many others used to describe the geometry of a black hole horizon. "\... in gravity we do not allow arbitrary quantum states on arbitrary geometries. There are constraints that the geometry must satisfy." Yes. These are called the Gauss, diffeomorphism and Hamiltonian constraints. Again, a very standard part of LQG. "A version of this has already been accomplished in \... As reviewed in Section 3, these models add degrees of freedom that "live on the links"." They do? You don't mean the way that spin-networks have spin degrees of freedom living on their edges labelled by representations of SU(2)? "different states of these link degrees of freedom can be interpreted as different geometries" Yes. They can indeed. Each edge has associated with it a quantum of area - again discovered thirty two years ago by \@carlorovelli and Lee Smolin, whose eigenvalue is given by the Casimir of the corresponding spin label. "\... and the link degrees of freedom can be made to satisfy constraints (such as Gauss' law)." No. They can't "be made to" \... they do satisfy Gauss' law. Again this is the Gauss constraint of the connection formulation of GR from which LQG is derived. I mean, I get it. Demagogues like Leonard Susskind and David Gross decided at one point that LQG was bullshit. String theory was the one and only truth. So nobody outside the LQG community gave a damn what we had accomplished over several decades. Then Brian Swingle and Xiao Gang-Wen come along with MERA and "spin-nets" - real discoveries btw, not old wine in new bottles like modern day "holographic tensor networks". Suddenly people start to realize that maybe this graph based approach is more fruitful. Then there is the big breakthrough in 2014-15 by Almhieri, Dong, Harlow, Preskill, Pastawski and Yoshida in which they show the connection between quantum information, error correction and the description of bulk geometry in AdS in terms of the boundary CFT. What is the principle tool they use for this purpose? Tensor networks. As an aside, in 2013, Xiao-Liang Qi had already discovered an exact holographic mapping from bulk to boundary states in a much overlooked paper (1309.6282), again in the language of tensor network states. Now, everybody in the "string community" starts jumping on the tensor network bandwagon. And that's great. Its just the rest of us in LQG are watching with a feeling of horror and disappointment that the structures we discovered decades ago are now being rediscovered by people who claim to be doing string theory. Even though, on the face of it, there is no direct connection between spin-networks and string theory. There is actually, but more on that in a later post. Pretty soon one or more of these researchers will "discover" \@carlorovelli's 1996 calculation of black hole entropy using "holographic tensor networks" and everybody from \@QuantaMagazine on down will rush to hail it as the breakthrough of the century. In any case, this is what underlies the derivation of the Ryu-Takanayagi formula from tensor networks. Now, what is indeed novel and revolutionary is the relation to quantum information. However, even this is not THAT novel. For instance here are two papers - (again of zero significance as per the "strings" community) from 2005 and 2006, well before the 2014-15 papers of Almhieri et al: "Reconstructing Quantum Geometry from Quantum Information: Spin Networks as Harmonic Oscillators" (2005) by Girelli and Livine (gr-qc/0501075) "Reconstructing Quantum Geometry from Quantum Information: Area Renormalisation, Coarse-Graining and Entanglement on Spin Networks" (2006) by Livine and Terno (gr-qc/0603008) They didn't discuss the relationship between quantum error correcting codes and spin networks, but they laid the basic foundations for understanding spin networks (and thereby quantum gravity) in the language of quantum information. And even prior to Livine and Terno's work, there is work by Marzuoli and Rasetti describing the intimate relationship between quantum computation and spin networks: "Spin network setting of topological quantum computation" (2004), Marzuoli and Rasetti (quant-ph/0407119) Other than that there is my own short paper from 2013 where I show that one can view elementary particles as topological excitations in spin network states and that there particles can be understand as playing the role of gates for universal quantum computation. "Elementary Particles as Gates for Universal Quantum Computation" (2013), Deepak Vaid (1307.0096) I tried to publish it, but it got sent back from the editor's desk. Maybe if I had mentioned "string theory" a sufficient number of times it would have gotten through. And then this work from 2019 where I point that these same topological excitations form the basis of the GHZ code one of the core elements of many quantum error correcting algorithms: "Quantum Error Correction in Loop Quantum Gravity" (2019), Deepak Vaid (1912.11725) Of course, none of this is to say that the work being done with holographic tensor networks is not important or novel. Of course it is. The most glaring deficiency of the LQG community is how we have completely ignored the AdS/CFT correspondence to our own great detriment. However, in science it is of fundamental importance to give credit where credit is due. Without this we are nothing more than a band of rapacious Wall Street financiers out to cut our competition's throat. The holographic tensor network community needs to recognize that acknowledge that much of what they are now calling "novel" was discovered more than three decades ago. Of course, they don't have to. In fact we could all pretend that LQG never even existed. If it is possible to pretend that Palestine was never a nation then surely the existence of LQG and spin-networks can also be dismissed with far greater ease. But in doing so we would be doing a great disservice to the history and ethos of Science.
