---
title: "Fluctuation Dissipation in Quantum Gravity"
date: "2017-08-09"
categories: []
slug: "fluctuation-dissipation-in-quantum-gravity"
---
In statistical mechanics we are mostly concerned with the statistical averages of various physical quantities when the system is in equilibrium. Fluctuation is a common phenomenon in nature. Fluctuation means how much a quantity deviates from its average value. The average value of the thermodynamic observables and the size of their fluctuation about their equilibrium values can be predicted by equilibrium statistical mechanics. In a macroscopic system, by using fluctuation we can understand many physical phenomena. When the thermodynamic system is small, increasing thermal fluctuations affects the behavior of thermodynamic quantities such as specific heat, compressibility and and other susceptibilities. If we apply a small external force to an equilibrium statistical system, the mean value of the random variable will respond to this force. We can deduce this response by using fluctuation dissipation theorem. Brownian motion requires both the velocity and position of the particle. But in a realistic situation like colloidal particles suspended in water, we can eliminate the velocity variable, by using Markovian dynamics to describe the position variable. This is a typical example for the model of the same physical system by two different levels of description. Mathematical procedures are used to relate the reduced and simplified descriptions in the statistical mechanics or generally the process of model analysis to more detailed and fundamental equations. Albert Einstein established a relation which connects the macroscopic diffusion constant $D$and atomic properties of matter$D=\frac{k_B T}{6\pi \eta a}$where$T$is the temperature ,$\eta$is the viscosity of the liquid and$a$is the Brownian particle's radius. **Langevin equation** The simplest method to understand the dynamics of non equilibrium system with the help of the theory of Brownian motion. Langevin equation is the most elementary equation, which contains both frictional forces and random forces. Fluctuation dissipation theorem connects these two phenomena. Brownian motion is an unpredictable type motion when a heavy particle is immersed in a liquid. It was first observed by botanist Robert Brown in 1827. In 1905, Albert Einstein and in 1906, Smoluchowski independently gave the first theoretical explanation of Brownian motion. Albert Einstein explained Brownian motion based on the molecular kinetic theory of heat in a paper, which provides definite theoretical conformation that atoms and molecules actually exist. The inertia of such particle was not considered in the first model. Considering the effect of inertia, in 1908 P. Langevin proposed a more detailed explanation of Brownian motion. Motion of ions in water or reorientation of bipolar molecules and many other phenomena could be successfully explained using the theory of Brownian motion. Real world applications of mathematical model of Brownian motion is the stock market fluctuation. Motion of a dust particle execute random motion, it could not be explained using equations like Newton's or Hamilton's equations. Consider a one dimensional Langevin model, a Brownian particle at a position$x$. Fluid's motion depends on two forces acting on the particle of mass $m$. One is the frictional force $m\gamma \dot{\vec{x}}$, due to the frictional coefficient $\gamma>0$, and the other one is fluctuating force $\vec{F}$, due to the continuous effects of the fluid's molecules on the particle. The external force, which does not depend upon the velocity of particle, is called Langevin force. Brownian particle is said to be free, if there is no potential. Then the Langevin equation becomes $m\ddot{\vec{x}}=-\gamma \dot{\vec{x}}+\vec{F}$By Stokes theorem$\gamma=6\pi\eta a$. We can split the force $\vec{F}$into two parts$\vec{F}=-\nabla V+\vec{f}(t)$ $V$is the fixed background potential in which the particle is moving,$\vec{f}(t)$is the random force. Langevin equation is a stochastic differential equation, because we dont know what actually the random term$\vec{f}(t)$is. The solution for above equation with given initial conditions is also a stochastic process. To fully define the Langevin model, we need to specify the statistical behaviors of the random force. Assume the random force is negliible,$m \frac{d}{dt}=-\gamma$ $\frac{1}{\gamma}$is sometimes noted as mobility$B$. $= exp(-\frac{t}{\tau})$where$\tau=\frac{m}{\gamma}=mB$, is the relaxation time. Using relaxation time, we can calculate the mean drift velocity of the particle. The ultimate value of the velocity of Brownian particle is zero. In equilibrium, we have equipartition theorem, so this cannot be true. $_{eq}=\frac{K_BT}{m}$We have$_{eq}=e^{-\frac{2 t}{\tau}}_{eq}\rightarrow 0$So inorder to get the correct equilibrium , random force is required in the above expression. The fluctuation force is arises due to occasional impacts of the Brownian particle with molecules of the surrounding medium. it will vary extremely over the time of any observation. So we can concluded this as$=0,\\,\\,\\, =2 D\gamma ^2\delta_{ij}\delta(t_2-t_1)$