---
title: "Specific Heats of AdS Black Holes and Quantum Geometry"
date: "2019-08-25"
categories: []
slug: "specific-heats-of-ads-black-holes-and-quantum-geometry"
---
# Schottky Peaks and AdS Black Holes

In [@Johnson2020Specific], Clifford Johnson makes yet another contribution to the study of black holes in anti-deSitter spacetimes or AdS black holes, for short. In this work he studies those black holes for which the specific heat at constant volume $C_V$(with "volume" here referring to the volume of a spatial slice of the spacetime with the volume of the black hole excluded:$V = V_{AdS} - V_{BH}$) does not vanish. He points out the odd fact that for systems such as AdS-Schwarzschild and AdS-Reissner-Nordstorm (which is basically the charged version of the AdS-Schwarzschild black hole) $C_V = 0$. The reason this is odd is that the thermodynamic phase space of these spacetimes maps exactly onto that of a classical van der Waals (vdW) gas of weakly interacting particles. Such systems possess a non-zero $C_V$. In particular, $C_V(T)$as a function of temperature yields important information about the microscopic degrees of freedom which contribute to the thermal behaviour of the system. For instance, for a gas of weakly interacting molecules below a certain temperature only the translational degrees of freedom contribute to the overall energy. However, above a certain minimum temperature the rotational and vibrational degrees of freedom of the molecules begin to get excited. This contributes to a jump in$C_V(T)$above that minimum temperature. In this sense, he points out,$C_V(T)$is a direct measure of the degrees of freedom available to the system while keeping the volume constant. The fact that certain AdS black holes exhibit vdW type behaviour yet have zero$C_V(T)$is therefore somewhat strange. He then goes on to study systems such as AdS-Kerr (rotating black holes) and something known as the AdS-"STU" black hole. In these systems he finds that$C_V(T)$is not identically zero and at certain values of the temperature this quantity exhibits jumps which are known as Schottky peaks in the condensed matter literature. He exploits this fact in an accompanying paper [@Johnson2018Holographic] to point that holographic heat engines (engines which use AdS black holes as their "working substance") can be viewed as quantum heat engines in a manner analogous to a system such as a three-level maser. For me, however, what is most interesting is his statement regarding AdS black holes that due to the fact that$C_V(T) = 0$: "*while the phase structure of these black holes are strikingly similar to that of ordinary matter systems, in this regard they are pointedly different*". Here I would like to point out that given what we know about quantum gravity and quantum geometry it is not only *not* strange, but also completely natural that such systems *must* have a vanishing constant volume specific heat!

# Quantum Geometric Degrees of Freedom and $C_V$What we learn from loop quantum gravity (LQG) is that the geometric degrees of freedom such as lengths, areas, volumes and even angles are quantized at the Planck scale and have a spectrum with minimum non-zero eigenvalues. The atomic constituents of spacetime which are therefore responsible for the thermodynamic behaviour of macroscopic (semi-)classical geometry are the "grains of space" represented by quanta of geometry - more specifically the eigenstates of the volume operator of LQG. Once this picture is in hand, it becomes manifestly clear as to why$C_V(T)$ *must* be zero for such systems. This must be the case because the degrees of freedom which contribute to the specific heat are *precisely* those which contribute to the total macroscopic volume of the system. If the system is kept at *constant volume* that implies that we cannot create or destroy the fundamental excitations which contribute to the total energy of the system. Therefore the specific heat of the system under such a constraint *must* vanish.

# Rotating and Charged Quanta of Geometry

However, this cannot be the full picture. As Johnson points out there are systems, such as AdS-Kerr and AdS-STU, which do possess non-zero $C_V(T)$. In the case of AdS-Kerr the non-zero $C_V(T)$can be attributed to the angular momentum of the spacetime. Translated to the LQG picture, this tells us that in Kerr-AdS the individual grains of space - represented by the quanta of the volume operator - must carry *additional* degrees of freedom beyond the usual geometric ones. These additional degrees of freedom represent angular momenta of the volume quanta and contribute to the overall angular momentum of the macroscopic geometry. Consequently, even at constant volume - keeping the number of grains of space fixed - one can change the energy content of the system by exciting the rotational degrees of freedom of the volume quanta leading to a non-zero value of$C_V(T)$for such a system. The situation for AdS-STU black holes is somewhat different. There the non-vanishing value of$C_V(T)$arises due to the non-zero values of a set of four charges, labelled$H_1, H_2, H_3, H_4$associated with four separate$U(1)$scalar fields. When all the charges are equal the STU solution reduces to the familiar AdS-Reissner Nordstorm solution with a single type of charge, and with$C_V(T) = 0$. The non-zero $C_V(T)$of the STU solution therefore arises due to the coupling between volume quanta which carry different species of charges. When all the species of charges are the same, this inter-atomic coupling vanishes and we are again left with$C_V(T) = 0$. However, when there is more than one type of charge, the possibility of a coupling between volume quanta carrying different species of charges leads to the possibility of a non-zero $C_V(T)$.