---
title: "Battling Depression: A Personal Account (Part 1)"
date: "2023-02-03"
categories: []
slug: "battling-depression-a-personal-account-part-1"
---
# Prologue

Depression is a terrible disease. What amplifies its debilitating effect is its invisibility. There are no physical symptoms apparent to the external observer. In the absence of any concrete diagnostic criteria via either brain imaging or biochemical analysis, its presence must be inferred only indirectly and based primarily upon the testimony of the afflicted individual. Due to this reliance on personal testimony rather than on objective evidence, it is easy to dismiss the existence of depression in an individual as simply being an "imagined" affliction rather than a genuine pathology. To make matters worse, from time to time so-called "gurus", "sadhgurus" and other "moral leaders" setback the cause of mental illness education by decades by declaring that "most depression is self-created"! In light of this lack of social acceptance of the reality of mental illness it becomes imperative that those who have suffered or are currently suffering from any form of mental illness should come out of the shadows and reveal their condition to the world and provide testimony to the fact that depression is not only very real but also treatable and nothing to hide or be ashamed of. It is *not* a self-created problem anymore than flu or malaria are self-created. It is a disease whose complete origins we have yet to understand, but what is clear, is that with proper medication and therapy depression can be managed allowing people to lead their lives without the constant torment and mental turmoil associated with this illness. **I have been suffering from clinical depression since I was about fourteen years old.** I lost a major portion of my teenage years to depression. I was late by four years in joining college because of two lost years between 10th and 12th grades and another two years lost following 12th grade. As a young boy I had become intensely fascinated with physics. I read Stephen Hawking's classic *Brief History of Time*, Asimov's *Atom*, *Superforce* by Paul Davies and Gamow's *The First Three Minutes*. At the same time I devoured Ronald W. Clark's epic biography of Albert Einstein. However, as was expected of any well-trained Indian child from that era - not that those expectations have evolved a great deal over time - I was expected to score top marks in my regular classes and to eventually score a top rank in one or more of a dozen different entrance examinations and bag a coveted seat in a top-ranked engineering school. Of course, none of these things happened.

# Onset

Around 8th grade, I rapidly started to realize that I was a fish out of water. There was no room for creativity, open-mindedness or independence - whether social or academic - in the suffocating social environment of the Indian middle and upper middle classes to which my family belonged. I began to be viewed more and more as an oddity. A highly intelligent oddity with great potential but an oddity nevertheless. It also just happens to be the case that there is a general inclination towards mental illness in my extended family. There is no clinical evidence for this since I am the only one in my family to actually have acknowledged my problem and to have gotten treatment for it. But there is plenty of anecdotal evidence and experiences collected over the years which leave little room for doubt that several members of my extended family tree suffer from one or the other form of depression/mental illness. Further my family life was deeply disturbed. Ours was not a happy family by any stretch of the imagination. I have three sisters, two older and one younger. I don't want to pin any blame for all the fights, arguments and drama our family members participated in on nearly every day of the year. It could be that everybody else in my family was a perfectly well-balanced individual, that my parents made no mistakes in bringing up four precocious children, and that it was only my own selfishness and misbehavior which caused all this constant turmoil in our family. The precise cause is not as important as the end result this situation had on me. It meant that I lived in a near constant dread of returning home. I tried to find refuge anywhere I could - spending time as much time at the homes of various friends as decency would permit, taking walks in the roads near my home until hunger beckoned, moving to my Mama's (Mother's brother) home or to the home of my Bua (Father's sister) and long over staying my welcome at both places by weeks or months. Each of these escapes provided only a temporary reprieve from the utter collapse of my emotional self which awaited me on the inevitable return to my own home. And finally one day in the spring of 1995, sometime after my fifteenth birthday, I ran out of places to escape to. That day I awoke to find myself involuntarily admitted to the psychiatric ward of one of Delhi's allegedly "better" government hospitals.

# Misdiagnosis and Mistreatment

As I was told years later, the story goes like this. I was sitting and reading the newspaper on the sunlit balcony of our 7th floor government flat when I was found unconscious and unresponsive by my Fufa (Father's sister's husband), someone who I was always felt very close to and whom I always believed to be one of the only individuals in my world who understood what I was going through. Of course, why you would take an unconscious and unresponsive individual to a psychiatric ward instead of just a regular emergency ward has never been made entirely clear to me. In hindsight it is not surprising that to those around me I would have appeared to clearly be in need of some sort of psychiatric treatment. By that age (15) I had come to the conclusion that I was living in a severely broken society where dogma, blind faith and superstition prevailed over curiosity, reason and criticism and where someone like myself who cared more about doing what I thought was the right thing than about keeping up appearances was never going to be fully accepted. The only problem was that I was not smart enough to keep my observations to myself and to assume that there actually was an appetite in those around me - my family, friends, classmates, teachers and others - to hear what sounded like the unending whining of a spoiled son of a highly privileged upper middle class Indian family. I was promptly diagnosed, or misdiagnosed as I would later come to understand, with "paranoid schizophrenia" by an allegedly famous psychiatrist (Dr B. R. Agnihotri), who to me appeared to be in urgent need of psychiatric help himself. I was forced to take several rounds of electroconvulsive therapy. As an underage person I had no say in the matter. I remember quite clearly being rolled down the hall in a medical cart to the ECT station. There I would plead and beg with the "gentle" doctors and nurses around me not to go ahead with the procedure. But as I was held down by several pairs of hands, a gag was placed in my mouth to prevent me from biting my own tongue and at the flick of a switch large amounts of electric current were sent surging through my skull. I would wake up at some undetermined time in the future, with my head groggy as feeling as if I was in a mental fog. Exactly how many times I underwent this barbaric treatment I do not know. As someone who viewed their brain as their most precious asset I was not pleased that my cerebellum was being subjected to high voltage shocks in the misguided hopes of ameliorating my non-existent schizophrenia. After repeated pleading with my parents I was finally discharged from that hospital and taken home. However, every movement I made was assiduously monitored either by the junior government peons assigned to my father by virtue his job as a high ranking civil servant or by my own family members. I was compelled, on threat of being returned to Dr Agnihotri's "care" in Govind Ballabh Pant Hospital, to take the anti-schizophrenia drug Clozapine. Most likely as a consequence of this medication I developed a form of [tardive dyskinesia](https://www.webmd.com/schizophrenia/tardive-dyskinesia) which still manifests itself today in the urge to compulsively touch certain objects in my immediate environment in certain patterns for no apparent reason. Usage of Clozapine can also lead to several [life-threatening conditions](https://www.pharmaceutical-journal.com/learning/learning-article/how-clozapine-patients-can-be-monitored-safely-and-effectively/11138788.article) in patients. Regular blood tests are required to monitor for the presence of any of these conditions. Once every month or so I would be dutifully escorted to a clinician for this painful ritual. This continued for a year and a half or so. Of course, I don't remember the exact duration. In fact, due to the ECT most of my preexisting memories had been irreversibly mangled and the ability to form new memories appeared to have been severely degraded. It was a daily struggle for me to continually remind myself how important it was for me to not forget what I had experienced and to surrender into the welcoming embrace of a numb and hazy existence where I accepted all that had happened and all that was happening without any resentment or anger. Some years later, when I was nineteen or so, after succumbing to a combination of angry demands and desperate pleading my mother accompanied me back to the hospital in order to allow me to inspect my medical file. I remember sitting in front of two doctors along with my mother as I demanded that I be allowed to see my file. After some time an underling was dispatched to procure the file. I waited with great eagerness to see the documentation which would prove beyond a doubt the horrors I had been subjected to as a fifteen year old. Finally the office peon came back carrying a file folder. In what would have come as no great surprise to a smarter person, but came as a shock to me, the folder was indeed there, but it had no contents! Not a single shred of paper. Not a single record of admission, or discharge. Not a single record of the medications I was given or the treatments I was administered or the doctors who prescribed them. I soon understood that a perverse drama was being played out for my benefit, through which my parents could claim that they had made every effort to allow me to inspect my medical history but it just so happened that those documents had been "accidentally misplaced" by someone in the intervening gap of around four years. Of course, it could be that my parents had no role in the apparent disappearance of my medical record. But you know that feeling you get when you realize you're being played for a chump by those around you? That feeling was as strong as it could be in me at that moment.

# Aftermath

Once the initial ECT generated haze started to subside I started to read every piece of information I could find, online and offline, on mental illness and schizophrenia. It became abundantly clear to me that no sane person could say that my symptoms were those of schizophrenia rather than of the rather less severe, but still debilitating, condition of clinical depression. No amount of explanations or entreaties on my part could convince my parental guardians that the so-called "famous" psychiatrist had made a misdiagnosis. Of course, accepting this would also imply acceptance of their own role in my mistreatment at the hands of a narcissistic quack and I lived in an age where accepting ones mistakes, especially where your children were concerned, was considered a sin. In a manner of speaking, my greatest mistake was living in a society in which disagreeing against social norms was considered a sign of madness. From this perspective it didn't really matter that I did not, in fact, exhibit the symptoms of clinical schizophrenia. To be declared a schizophrenic in India in those days, it was sufficient to be a person who believed they should follow their own dreams rather than those foisted upon them by social and cultural dogma. The ECT sessions caused substantial permanent memory loss. I have only very vague memories of that period in my life. If I am able to recount any details it is because I worked very hard at the time to commit those facets of my experience to my memory for future retrieval. The effects of clozapine on my non-schizophrenic brain, were no less severe. Clozapine is an extremely strong anti-psychotic. Anti-psychotics are given that name because their use is to combat psychosis. Their action on the brain and the resulting physiological effects are not subtle. This is necessarily the case since psychosis by its very nature is a manifestation of extreme, uncontrollable behavior. Giving anti-psychotics to a non-psychotic person is like putting a hammer to their brain. Fuzziness, drooling, tardive dyskinesia and a dozen other unpleasant side-effects can be the result of using drugs such as Clozapine. My family, friends and close relatives all observed and were subjected to the resulting erratic traits in my behavior. Of course, they attributed these traits to my "mental illness" and not to the fact that I was being the wrong medicines. I can't blame them for this, though. They didn't know any better. They couldn't have known any better. I belonged to an upper middle class family and my close family came from a background of traders and salespeople. Knowledge of the functioning of biochemical pathways, brain biochemistry, chemical and biological effects of anti-psychotic medication was as alien to them as the idea that a child might want to determine its own destiny and path in life. Eventually, after much begging, pleading and bargaining my parents consented to allowing me to stop using Clozapine. I suppose, when they realized that they couldn't force me to take the pills without resorting once more to involuntary commitment in a medical facility, they thought it best to cede the battle. We had all been through enough. I had already lost a great deal of time at what is considered a crucial juncture in the academic career of any future trailblazer. My parents, for all their faults, are still only human. Having to see their only son undergo such dehumanizing treatment could not have been easy for them either. That experience must have left them more drained and broken than I could possibly comprehend at that time being so deeply overcome by my own despair and anger at the course my life had taken thus far. (to be continued\...)

------------------------------------------------------------------------