---
title: "My Life: A Personal Account (Part 2)"
date: "2024-12-27"
categories: []
slug: "battling-depression-a-personal-account-part-2"
---
This is the second in a series of posts detailing my personal battle against depression from the early teenage years uptil the present day. The first post can be found [here](https://www.quantumofgravity.com/blog/index.php/2023/02/03/battling-depression-a-personal-account-part-1/).

# Rebellion and Recovery

Rebellion and a general aversion to authority are traits which seem to be an inherent part of my genetic makeup. Perhaps it is these qualities which led to a great deal of pain and suffering which I endured as a teenager and a young man. But perhaps it is these same qualities which have led me to be the person I am today - uncompromising in my beliefs, unbowed in the face of personal and professional trauma and unrelenting in my desire to build a better life for myself and those I love. These traits have also bled into my professional life and in my approach towards research where I have refused to accept the dogma that string theory is the be all and end all of theoretical physics and have attempted to forge a path forward trying to cut through the tremendous amount of junk and clutter which constitute much of high energy physics these days. Whether this path will actually lead anywhere fruitful is yet to be seen. Before I describe the process of recovery from those dark days in my life I think it is important to describe the type of childhood and education I had.

# Early Years

The events described in [part 1](https://www.quantumofgravity.com/blog/index.php/2023/02/03/battling-depression-a-personal-account-part-1/) of this series occurred between spring of 1994 (as I turned fifteen) and late 1995 (halfway into my sixteenth year). Prior to these developments I was leading, by all accounts, the life of a normal, nerdy Indian schoolboy. I was more interested in reading and learning than I was in athletic and sports. I would spend more time in the library than on the playground. I had the awesome privilege of being born into the family of an IAS (Indian Administrative Service) officer. The IAS and IPS (Indian Police Service) are the two primary instruments via which power was wielded over colonial India by our British masters and after independence continued to be used in much the same manner by our new masters who were Indian in name and origin but whose relationship with Indian citizens was not much different from that between our erstwhile British overlords.

## A Humble Beginning

My father came from a humble background. His father, my grandfather, worked as as a "Munim" (accountant or book keeper) in a flour mill. He was a humble man with a humble salary. He had two sons and two daughters out of which my father was the clever one. He often recounted stories of how he grew up reading his school books under the light of a kerosene lamp sitting with his back against my grandmother's back as she worked on some household chores. His intellect and immense stamina for hard work led him to finish his schooling with the highest marks. Due to his academic performance he was accepted into Lucknow University where he did his BS (Bachelor of Science) and MS (Master of Science) in Physics. Perhaps it is not so strange that I ended up becoming a physicist in light of my father's own youthful aspirations. He wanted to become a physicist but life in those days was very hard and becoming a college professor would not allow him to lift his parents or his own family out of poverty. He briefly toyed with doing research on lasers at IIT Kanpur before devoting himself to preparing for the civil services examination. He passed that exam on his first attempt. In fact, he scored the top rank in the all India examination which allowed him to choose which branch of the civil services he wanted to join (he chose the IAS) and which state he wished to be his "cadre" (he chose his home state of Uttar Pradesh). As a newly minted IAS officer that too the all India topper he instantly vaulted to the highest ranks of eligible bachelors in the country. Consequently he was offered the hand of the beautiful nineteen year old girl, who was the daughter of a very prosperous trader from a neighboring state, and which his parents promptly accepted. In those days marriages did not happen out of love or choice. Your parents chose your mate for you and you were lucky if you even managed to see your future spouse before your wedding night. He was twenty-nine years of age and my mother was nineteen when they were married. By virtue of belonging to a wealthy family my mother had received her education in the best Christian convent schools in the country in the hill state of Sikkim. She belonged to the smaller than one percent of the people of our country at the time who were fluent in the English language. So was my father, but his fluency was due more to his own personal efforts than due to his early schooling which was in government run public schools where the medium of instruction was Hindi. She was the sophisticated one. He was the smart one.

## A Son is Born

The first three children they had were all girls. Of those one passed away as an infant. For a deeply patriarchal society as India was in those days - and continues to be in many ways until today - having a daughter was considered no less than a sin. I can only imagine what my mother must have suffered for not having produced a male issue. As my maternal grandmother recounted later in life, it was through the blessings of Lord Hanuman and various other Hindu deities, that I was finally born on the early morning of March 30, 1979 in a hospital in Kanpur, the city where my father was posted at the time. Just as being an IAS officer vaulted my father into the highest layers of the Indian social structure, being born a male meant that I was that was much more valuable than any number of daughters. Of course my coming meant that my mother could now stop having children. However, I suppose the expectation that fates might smile one more time in the form of another son led to her having one more child after me. The child also was a daughter. So there we were. Three girls and one boy. I think that was already more than they could handle and I remember the early morning in Kanpur when the doctor came to our official residence to perform a vasectomy on my father. I can only imagine the joy and relief which must have filled my tired and sleep deprived mother's heart on that day.

## Edelweiss

My pre-primary education was conducted in a school called "Wendy's" in Kanpur. Of course, this school has no relation whatsoever with the American fast food chain of the same name. As I was turning five my father was transferred from Kanpur to the beautiful hill station of Nainital located in the foothills of the Indian himalayas. Nainital was, and is, a place of pristine beauty. Not too high up in the mountains as to be inaccessible but just high up enough to be used as the official summer residence of the British viceroy prior to India's independence. The massive, palatial mansion which was built for this purpose is known as "Governor's House" or "Raj Bhawan" and is located on acres and acres of pristine hillside forests with its own exclusive golf course. The setting was not much different from the idyllic mountain retreats portrayed in that eternal classic "The Sound of Music". (to be continued)