---
title: "Comment on &quot;A Post-Quantum Theory of Classical Gravity&quot;"
date: "2019-02-01"
categories: []
slug: "comment-on-a-post-quantum-theory-of-classical-gravity"
---
Sometime ago Jonathan Oppenheim, one of the brightest minds [@Horodecki2005Quantum; @Oppenheim2010For-Quantum; @Oppenheim2010The-Uncertainty; @Horodecki2011Fundamental; @Brandao2013The-Second; @Kollmeier2014The-Photon; @Yunger-Halpern2016Microcanonical; @Woods2016Autonomous; @Masanes2017A-General] in the frontiers  of quantum information and quantum foundations, posted a very interesting article [@Oppenheim2018A-Post-Quantum] on arXiv. As is the custom these days, he announced the paper in a series of tweets, starting with:

> A post-quantum theory of classical gravity? <https://t.co/uNbsbZ2AYq>
>
> A consistent theory of classical gravity coupled to quantum field theory that reduces to Einstein's equations in the classical limit. The assumption that gravity is classical necessarily modifies quantum 1/3 --- Jonathan Oppenheim (\@postquantum) [November 9, 2018](https://twitter.com/postquantum/status/1060874831959375872?ref_src=twsrc%5Etfw)

Now, while the work itself is a tour de force of mathematical and physical insight, in my humble opinion, there are several shortcomings in the basic idea. I mentioned these shortcomings in brief in my own series of tweets:

> There are several problems with this idea. I will list them here and elaborate on them elsewhere. <https://t.co/7Emx08julE>
>
> --- Astroboy (\@lqgist) [November 10, 2018](https://twitter.com/lqgist/status/1061364420750819334?ref_src=twsrc%5Etfw)

This post is about elaborating on these points as I promised in my tweet. There are two major parts of Oppenheim's work which are subject to criticism. The first is the assumption that:

> "since space-time describes causal structure and relationships between the matter degrees of freedom, that it is a-priori and fundamentally classical."

If, for the sake of argument, one grants the possibility that space-time is a-priori and fundamentally classical, then the next question is to ask whether Oppenheim's proposed framework for quantum matter coupled to stochastic classical gravity can avoid the pitfalls faced by classical gravity. In this post I will address the first aspect - must gravity be quantum?

# Must Gravity Be Quantum?

This, of course, is the crux of the matter. *Must*, after all, gravity be quantum or *must* it be quantized? There are the classic papers on this such as the argument for the necessity for quantum gravity by Hannah and Eppley [@Eppley1977The-Necessity] which unfortunately was shown to be flawed ^[1](#fn-685-Backreaction-Hannah-Eppley)^ by Mattingly [@Mattingly2006Why-Eppley]. There are several other very good motivations for seeking a quantum theory of gravity. Let us look at some of these.

## Singular Spacetimes

The best indicator of the range of validity of any physical theory is the point when the equations of that theory fail to provide physically reasonable solutions. For classical electromagnetism, this point occurs when one tries to describe the phenomenon of black body radiation in terms of equipartition of energy between the different radiation modes in a black body cavity. The resulting expression for the black body spectrum, called the Rayleigh-Jeans law, gives the right answer for the total emissivity of the black body at low wavelengths, but fails completely as we go to lower wavelengths and thus higher frequencies. The resolution of this difficulty lay in Planck's quantum hypothesis and his resulting modification of the Rayleigh-Jeans distribution. Another failure of classical physics is in the planetary model of atomic structure. If electrons are to be thought of as orbiting a positively charged nucleus, then - since any any accelerating charged particle emits radiation, and a particle in a circular orbit is undergoing constant acceleration - should they not continuously emit radiation causing their orbits to collapse into the nucleus? Clearly, this does not happen because we observe the existence of stable states of matter around us rather than short-lived states which collapse and die in massive bursts of energy. Classical gravity experiences analogous failures in regions of spacetime where energy densities and temperatures are very high. Such regions correspond either to the interiors of black holes or the big bang/crunch at the start/end of the Universe. Both, black holes and cosmological spacetimes, generically possess *singularities* - regions of spacetime where the background curvature increases without bound. The hope is that a theory of quantum gravity would permit a modification of the notion of a smooth and continuous geometry in such a way that regions where singularities *would* have formed in the classical description would instead be described in terms of a quantum gravitational state where the spacetime does not possess a unique metric but is instead described by a superposition of fluctuating metrics. While the classical geometry in such a region would be ill-defined, physical evolution of states of matter and geometry in such a region would certainly be well-defined.

## Hawking Radiation and Black Hole Evaporation

Classical gravity cannot account for the non-zero entropy of black holes. A non-zero entropy of any system implies the existence of microstates. While the horizon of Schwarzschild black hole solution of Einstein's equation is a smooth surface, the non-zero entropy of the black hole [@Bekenstein1972Black; @Bekenstein1973Black] implies that the apparently smooth surface must instead consist of many small pieces, each an independent degree of freedom which can contribute to the overall heat content and, thereby, to the total entropy of the system. The non-zero entropy arises from the fact that these small pieces can be arranged in many different way to yield the same macroscopic horizon structure. Soon after Bekenstein's discovery of the existence of black hole entropy, Hawking realized [@Hawking1974Black; @Hawking1975Particle] that the horizon would not be stable with respect to fluctuations of quantum fields in its vicinity. Particle-antiparticle pairs created from fluctuations of the vacuum quantum fields close to the horizon, would not annihilate as would be the case in flat space. Instead, one member of the pair would be pulled into the horizon, while the other would escape to infinity. It turns out that, with respect to an observer at infinity, the particle falling into the black hole has a *negative energy* (because inside the horizon time-like directions become space-like and vice-versa). Such an asymptotic observer would see a flux of particles coming out of the black hole whose mass (and area) would simultaneously be shrinking. However, analogously to what happens in the problem of classical black body radiation, the endpoint of the Hawking evaporation process cannot be described consistently within the framework of quantum fields on curved space which works so well to predict the existence of Hawking radiation in the first place. The temperature of the black hole is inversely proportional to its mass. Thus as its mass reduces, the temperature increases without bound and the black hole must emit an infinite amount of energy before it completely evaporates. This is reminiscent of the "ultraviolet" catastrophe of the late 19^th^ century. Once again, the hope is that quantum gravity would regularize the process of late-term evaporation of a black hole in much the same way that Planck's introduction of the quantum hypothesis, and the resulting replacement of the Maxwell-Boltzmann distribution by the Bose-Einstein distribution for bosons, regulated the high-frequency behavior of the radiation flux of a black body. In the case of the black body problem the "ultraviolet catastrophe" is prevented by dropping the assumption that black body radiation can be emitted as electromagnetic waves of *any* frequency. Similarly, here the "Hawking radiation catastrophe" can be resolved by dropping the unstated assumption that geometric observables such as areas and volumes can take values in a continuum, and instead are *quantized* taking on only certain discrete values.

## Holography and AdS/CFT

There is by now a vast amount of evidence for the so-called "AdS/CFT" or "holographic" or Maldacena conjecture, according to which the physics of a bulk spacetime can be encoded into a field theory living on the boundary surface of that spacetime. The roots of this conjecture can be traced back to the problem of black hole entropy and questions raised by the existence of Bekenstein's relation. The fact that the entropy of a black hole depends on the *area* of its boundary (the "horizon"), rather than on the *volume* contained within the boundary - as is the case with ordinary thermodynamic systems such as an ideal gas - already points us in the direction of a "holographic" viewpoint of black hole physics. Reasoning along these lines propelled first Gerard 't Hooft in 1993 [@t-Hooft1993Dimensional] and shortly thereafter Leonard Susskind in 1994 [@Susskind1994The-World] to formulate what is now referred to as the "holographic conjecture". A few years later Maldacena provided the first explicit example [@Maldacena1998Wilson] of how holography could be used to calculate expectation values of physical observables ("Wilson loops" in his original paper) living in the boundary field theory of a five-dimensional bulk spacetime with Anti-de Sitter (AdS) geometry. Shortly thereafter work by Gubser, Klebanov, Polyakov and Witten [@Gubser1998Gauge; @Witten1998Anti] provided the first general recipe for how correlation functions in boundary field theories could be calculated by understanding the behavior of gravitational fields in the bulk. As of now, the holographic conjecture is no longer considered a "conjecture", given the *vast* amount of evidence [@Natsuume2014AdS/CFT; @McGreevy2010Holographic; @Erdmenger2012Introduction; @Sachdev2015Bekenstein-Hawking] that has accumulated in its favor over the past two decades. In fact, we are at a stage where serious proposals [@Danshita2017How-to-Make; @Hashimoto2018Imaging] have been put forward for how to observe AdS/CFT in the laboratory! What is relevant for our discussion is that the holographic conjecture necessarily *implies* that any gravitational system possesses only a finite number of degrees of freedom. This is only possible if:

1.  There exists a minimal length scale at beyond which one cannot continue zooming into the spacetime manifold. Geometric observables such as lengths, areas and volumes are necessarily quantized at this scale.
2.  A quantum theory of gravity cannot be given a description in terms of a field theory which has a infinite number of degrees of freedom in any given region.

Given the overwhelming preponderance of evidence coming from the three lines of argument presented above - singularity resolution, Hawking radiation and holography - that spacetime is discrete at the smallest scales it would appear to be unwise to attempt to construct a theory of quantum gravity in which the gravitational field is inherently classical and smooth. Nevertheless, Oppenheim has taken on this daunting challenge and his proposal does provide food for thought and forces us to re-examine our conclusion that gravity must be quantized and the steps leading up to this conclusion. In order to understand his proposal better we need to understand the basic idea behind the theory of "semi-classical" gravity. That, however, will the topic of another blog post :-) [/bibshow]

------------------------------------------------------------------------

1.  [See Sabine's [concise description](https://backreaction.blogspot.com/2012/01/eppley-and-hannahs-thought-experiment.html) of the original thought-experiment and of the flaws discovered by Mattingly. ]{#fn-685-Backreaction-Hannah-Eppley}
