---
title: "Shoucheng Zhang, 1963-2018"
date: "2018-12-14"
categories: []
slug: "shoucheng-zhang-1963-2018"
---
# In Memoriam

I never had the good fortune of meeting or personally knowing [Shoucheng Zhang](https://en.wikipedia.org/wiki/Shoucheng_Zhang). Nevertheless he has had a profound influence on my academic career. As the world learned sometime last week, Zhang passed away suddenly on December 1 "after fighting a battle with depression" ^[1](#fn-781-ZhangObituaryAPS)^. He was one of the world's greatest theoretical physicists and losing him at the young age of 55 is an incalculable loss for the physics community. Already in his relatively short career he had made gigantic contributions to condensed matter physics. However, his ideas permeated well beyond condensed matter and touched high energy and particle physics as well. He deserved to be awarded the Nobel prize, not once but several times over. I have tried to make a partial list of his major works each of which independently constitutes a major leap in its respective field. A few of these are listed below.

# Scientific Accomplishments

1.  **Chern-Simons Landau-Ginzburg Effective Theory of the Fractional Quantum Hall Effect**: It is well understood [@Jain2007Composite] that the integer quantum hall effect (IQHE) can be given an effective field theory formulation by adding the topological Chern-Simons term to the Maxwell action in $2+1$ dimensions. Zhang [@Zhang1989EffectiveFieldTheory; @Zhang1992The-Chern-Simons-Landau-Ginzburg] extended the effective field theory approach to cover the fractional quantum hall effect (FQHE). This approach gave results equivalent to the wave-function approach of Laughlin but in addition also allowed a mean-field understanding of the FQHE.

2.  **Phase Diagram of the Quantum Hall State** and discovery of **Quantum Hall Insulator**: In collaboration with Kivelson and Lee [@Lee1992Quasiparticle; @Kivelson1992Global] Zhang uncovered a global phase diagram for the FQHE which exhibits a phenomenon known as the "law of corresponding states" according to which states at different filling fractions $\nu$can be mapped to each other under certain transformations. This approach provided the foundation for later work by Dolan [@Dolan1999Duality] who showed that this law of corresponding states followed naturally from the existence of a$SL(2, \mathbb{Z})$ symmetry in the FQHE. The existence of this symmetry was later used by Bayntun and collaborators [@Bayntun2010AdS/QHE; @Bayntun2011Finite] to demonstrate a holographic realization of the quantum hall effect.

3.  **$SO(5)$ Theory of High-T~c~ Superconductivity**: Zhang's greatest achievement, in my opinion, was the development of a theory [@Demler1995Theory; @Zhang1996SO5-Quantum] which provides a unified description of the phase diagram of high-T~c~ superconductivity.
    ![Phase diagram of two cuprate superconductors where the external variable is the dopant concentration $n$on the left and the pressure$p$on the right. When the dopant concentration (or pressure) is low the system exhibits an anti-ferromagnetic (AF) phase at low temperatures. As the dopant concentration (or pressure) is increased, the AF phase disappears and after going through a region referred to as the "pseudogap" phase, the system enters a superconducting (SC) phase.](/wp-content/uploads/2018/12/cuprates-phase-diagram-300x227.png){alt="Phase diagram of two cuprate superconductors where the external variable is the dopant concentration$n$on the left and the pressure$p$ on the right. When the dopant concentration (or pressure) is low the system exhibits an anti-ferromagnetic (AF) phase at low temperatures. As the dopant concentration (or pressure) is increased, the AF phase disappears and after going through a region referred to as the " pseudogap"="" phase,="" the="" system="" enters="" a="" superconducting="" (sc)="" phase."=""}

    The two primary regions of the phase diagram, the antiferromagnetic (AF) and the superconducting (SC) regions, are described in the long-wavelength limit by effective field theories which are governed by the gauge groups $SO(3)$(for AF) and$U(1)$(for SC). Zhang's brilliant insight was that these two gauge groups could be obtained from a large group$SO(5)$via symmetry breaking. Of course, there are many possible larger groups which contain$SO(3)$and$U(1)$as sub-groups. What makes$SO(5)$unique is the fact that starting from a microscopic Hubbard model for the dynamics of electrons in the cuprate lattice, Zhang (in collaboration with Demler, Meixner, Rabello, Kohno and Hanke) [@Meixner1997Finite-Size; @Rabello1997Microscopic; @Rabello1998Microscopic] was able to show - both numerically and analytically that in the long wavelength group emergent excitations obey the$SO(5)$symmetry. This is where my relation with Zhang's work comes in. While at Penn State I was exposed to the gauge formulation of general relativity [@Romano1993Geometrodynamics] which lies at the foundation of Loop Quantum Gravity (LQG) [@Ashtekar2004Background; @Rovelli2014Covariant; @Vaid2014LQG-for-the-Bewildered]. My brownian motion like traversal through the space of ideas and papers eventually led me to the beautiful$BF$theory formulation of general relativity [@Randono2010Gauge; @Randono2010Gravity; @Westman2013Gravity; @Westman2015An-introduction; @Wise2009MacDowellMansouri; @Smolin2003General; @Baez1999An-Introduction] wherein one starts with a theory which has an action of the form:$$\label{eqn:bf-action}\nS_{BF} = \int d^4 x~ \Tr[ B \wedge F] = \int d^4 x ~ \frac{1}{2} \epsilon^{\alpha \beta \mu \nu} B_{\alpha\beta}^{IJ} F_{\mu \nu}^{KL} \delta_{IK} \delta_{JL} \\$where$B := B_{\mu\nu}^{IJ}$is an anti-symmetric (in the spacetime$\mu,\nu$indices) field (or "two-form" in more technical language) and$F := F_{\mu\nu}^{KL}$is the field strength tensor of a gauge field$A_\mu^I$, where the$I,J,K,\ldots$take values in the Lie-algebra of a gauge group. The precise gauge group depends on the value of the cosmological constant and whether our geometry is Lorentzian or Riemannian <sup id="fnref-781-EC-Table"><a href="#fn-781-EC-Table" class="jetpack-footnote">2</a></sup> :
<p><em>Table omitted from the static migration: homogenous-spacetimes.</em></p>
The action (\ref{eqn:bf-action}) is a topological action. The equation of motion for the field strength gives:$F = 0$implying that there are no local degrees of freedom. The topological symmetry is broken and local degrees of freedom are introduced by adding an interaction term to (\ref{eqn:bf-action}) of the form:$\label{eqn:bf-action-interactions}\nS_{B^2 F} = \int d^4 x~ \Tr\left[B \wedge F - \theta~B \wedge B \right] \\$where$\theta$measures the strength of the interaction term. After performing the Cartan decomposition of the gauge connection and the$B$field <sup id="fnref-781-Cartan-decomp"><a href="#fn-781-Cartan-decomp" class="jetpack-footnote">3</a></sup>, we obtain the action for general relativity with a cosmological constant$\Lambda$. The symmetry breaking term$\theta$determines the strength of Newton's gravitational constant$G$and the cosmological constant$\Lambda$in the resulting spacetime via the relation:$\label{eqn:bf-effective-lambda} \theta = \frac{G \Lambda}{6} \\$Now, <em>a priori</em>, there is no reason to think that there should be any relation between Zhang's$SO(5)$theory of high-T<sub>c</sub> superconductivity and Einstein-Cartan gravity. However, if one looks more carefully at the Lie-algebra structure of both the theories a striking similarity emerges. The Cartan decomposition can be used to write the gauge field$A_\mu^I$in the following form:$ \label{eqn:cartan-decomp}\nA^I{}_J = \left( \begin{array}{cccc}\n0 & \omega^0{}_1 & \omega^0{}_2 & \omega^0{}_3 & e^0/l \\
\omega^1{}_0 & 0 & \omega^1{}_2 & \omega^1{}_3 & e^1/l \\
\omega^2{}_0 & \omega^2{}_1 & 0 & \omega^2{}_3 & e^2/l \\
\omega^3{}_0 & \omega^3{}_1 & \omega^3{}_2 & 0 & e^3/l \\
\epsilon e^0/l & -\epsilon e^1/l & -\epsilon e^2/l & -\epsilon e^3/l & 0
\end{array} \right) \\ $where$\omega^a{}_b$represents the usual gravitational gauge connection,$e^a$is the gravitational tetrad,$\epsilon \in { -1, 0, 1 }$determines the sign of the cosmological constant and$l$is a length scale related to the cosmological constant by the relation:$\label{eqn:cosmo-length}\nl = \sqrt{\frac{3}{\Lambda}} \\$On the other hand in Zhang's$SO(5)$theory, one can construct an anti-symmetric five dimensional "Zhang" tensor$L_{ab}$which obeys the commutation relations of the$\mathfrak{so}(5)$Lie algebra:$ \label{eqn:zhang-tensor}\nL_{ab} = \left( \begin{array}{ccccc}\n0 & & & & \\
\pi^\dagger_x + \pi_x & 0 & & & \\
\pi^\dagger_y + \pi_y & -S_z & 0 & & \\
\pi^\dagger_z + \pi_z & S_y & -S_x & 0 & \nQ & -i(\pi^\dagger_x - \pi_x) & -i(\pi^\dagger_y - \pi_y) & -i(\pi^\dagger_z - \pi_z) & 0
\end{array} \right) \\ $where$Q$is charge operator for the superconducting phases,$\vect{S} = (S_x, S_y, S_z)$is the spin-operator which measures the Néel order parameter in the anti-ferromagnetic phase and$\pi_i$is an operator which measures the strength of the valence bond between neighboring sites in the underlying Hubbard model. Using the commutation relations of these operators one finds that the Zhang tensor satisfies the following commutators:$\label{eqn:so5-commutation} \left[ L_{ab}, L_{cd} \right] = i \left(\delta_{ac} L_{bd} - \delta_{ad} L_{bc} - \delta_{bc} L_{ad} + \delta_{ad} L_{bc} \right) \\$which are precisely the defining relations of the Lie algebra of$SO(5)$. Now if we compare (\ref{eqn:cartan-decomp}) and (\ref{eqn:zhang-tensor}) we see that it possible to make the following identifications between the variables on the gravity side and those on the condensed matter side:
<p><em>Table omitted from the static migration: so5-correspondence.</em></p>
This identification, if it stands scrutiny, implies that there is a direct correspondence between the different phases of high-T<sub>c</sub> superconductors and solutions of Einstein's equations. This work was published in 2017 in AHEP [@Vaid2013Superconducting].</p></li>
<li><p><strong>Four Dimensional Generalization of the Quantum Hall Effect</strong>: In [@Zhang2001Four] Zhang and Hu predicted the existence of the Quantum Hall Effect (QHE) in four spatial dimensions. In the usual 2+1D QHE, given the electric field, there is only one spatial direction orthogonal to it along which the Hall current can flow. In 4+1D, given an electric field, there are three different spatial directions along which the Hall current could flow. In order for a QHE to exist in 4+1D, therefore the charge carriers must carry an internal$SU(2)
$$

 spin degree of freedom and the direction of the spin determines the direction of the Hall current. Now, of course, we don't have access to four spatial dimensions, so the practical utility of this effect might be limited. However, it does point the way towards a possible realization of elementary particles as topological excitations in a quantum hall fluid.

4.  **Quantum Spin Hall Effect and Topological Insulators**: Zhang, alongwith Hughes and Bernevig first predicted [@Bernevig2006Quantum] the existence of the quantum spin hall state - which is a topological insulator state - in HgTe/CdTe heterostructure quantum wells. Zhang and collaborators also went on to experimentally observe this effect [@Konig2007Quantum] within one year of their prediction of its existence.

This was an achievement no less remarkable than Novoselov and Geim's discovery of a method for manufacturing graphene or Cornell and Weiman's observation of the first Bose-Einstein condensate. Yet, whereas these two discoveries were awarded the Nobel prize within five years of the date of discovery, Zhang's work was passed over for far longer. Of course, there might be many factors at work here, but his untimely passing without having been awarded Physics' highest honor only highlights the absurdity of denying the Nobel to those who happen to die before the Prize Committee gets around to recognizing their phenomenal accomplishments during their lifetime.

# A Personal Note on Depression

It appears unthinkable that a man of Zhang's talents and accomplishments would take his own life at the peak of his career. Of course, suicide among physicists is not an unknown phenomenon. Boltzmann and Ehrefest are two well-known examples. However, both faced difficult personal circumstances. Boltzmann's work on thermodynamics and entropy attracted strong criticism and even derision from many of his peers. Ehrenfest, despite his towering talent, was not quite able to live up to his full academic potential. Zhang, on the other hand, was a celebrated physicist in his own lifetime. His accomplishments were globally recognized and he was a perennial favorite for the physics Nobel. Why then would such a person commit suicide? Depression is a terrible disease. What amplifies its debilitating effect is its invisibility. There are no *physical* symptoms apparent to the external observer. In the absence of any concrete diagnostic criteria via either brain imaging or biochemical analysis, its presence must be inferred only indirectly and based primarily upon the testimony of the afflicted individual. Due to this reliance on personal testimony rather than on objective evidence, it is also easy to dismiss the existence of depression in an individual as an *imagined affliction* rather than a genuine pathology. To make matters worse, from time to time so-called "Gurus" and "moral leaders" setback the cause of mental illness education by decades by declaring that "most depression is self-created"! In light of this lack of social acceptance of the reality of mental illness it becomes imperative that those who have suffered or are currently suffering from any form of mental illness to come out of the shadows and reveal their condition to the world. **I have been suffering from clinical depression since I was about fourteen years old.** As someone who has battled major depression to reach some level of professional success in theoretical physics I have some understanding of the personal struggle Zhang must have faced in his own life. The story of my own struggle is the topic of a separate blog post. This post is intended to be dedicated solely to the memory of one of the greatest theoretical physicists of our generation.

![Shoucheng Zhang\
February 15, 1963 - December 1, 2018\
Rest in Peace](/wp-content/uploads/2018/12/funeral-wreath-300x300.jpg){alt="Shoucheng Zhang <br /> February 15, 1963 - December 1, 2018 <br /> Rest in Peace"}

------------------------------------------------------------------------

1.  [https://www.aps.org/publications/apsnews/updates/zhang.cfm ]{#fn-781-ZhangObituaryAPS}
2.  [This table is taken from Sec 2.3 of [@Wise2009MacDowellMansouri] ]{#fn-781-EC-Table}
3.  [For details of this decomposition the reader may refer to [@Smolin2003General; @Vaid2013Superconducting; @Westman2015An-introduction; @Wise2009MacDowellMansouri] ]{#fn-781-Cartan-decomp}