---
title: "How to kill a great platform"
date: "2018-09-21"
categories: []
slug: "how-to-kill-a-great-platform"
---
There are few things in life more disappointing than watching a beautifully crafted, socially responsible, disruptive technology platform self-destruct from the inside out. With the launch of the so-called "web-extensions" versions of Mozilla Firefox - which now extends to the once reliable ESR (Extended Support Releases) branch - Mozilla has destroyed much of the appeal that Firefox once held for its community of loyal and devoted users and developers. This is a not a recent development. It started several years ago with the removal of version numbering from Firefox releases and the histrionic, overzealous defense of this inexplicable move by Mozilla's chief tech "evangelist". Many people, including me, at the time noted the strangely defensive and hostile responses to even the mildest criticisms of this odd move. What could possibly be gained by moving away from the venerable and highly informative practice of version numbering new software releases to one where the release number provides little or no information as to whether the latest update is major, minor or merely a bug-fix release? As it turns out, there was no actual benefit, other than for the "evangelist" and fellow ideologues to be able to loudly proclaim their unveiling of this alleged paradigmatic shift in Mozilla's software philosophy. That was just a hint of the unfortunate downward spiral of the Mozilla platform. The most recent move to the "web-extensions" API in the name of increased security has left countless Firefox users and extension developers completely clueless and dissappointed. What once was the core engine of Firefox's popularity and the entire basis of its challenge to the dominance of corporate sponsored platforms such as Google's Chrome browser or Microsoft's Internet Explorer - the almost magical ability to customize nearly each and every aspect of the browser's functionality with add-ons - has been eliminated in one swift move. A few of the most popular browser add-ons which don't work with the new Firefox, and given the strange and arbitrary security restrictions will likely not work in the near future, include Tabmix plus, Downthemall, Noscript, GrabandDrag among many others. Another aspect which affects a niche audience is the inability to be able to save files edited within the browser to a local disk via javascript. This implies that the beautiful "Tiddlywiki" single page blog platform is no longer usable from within the "new" Firefox. Mozilla's team will say, this is all in the name of security. How can Firefox compete with the more secure Chrome without revamping its basic architecture? Not being a Firefox developer myself, I cannot comment on the precise merits and otherwise of this revamping. However, being a coder with some level of experience in developing and hosting websites and hardly being a technological neophyte myself, it does seem pretty clear to me that Mozilla *could* have staked out a friendlier, less self-destructive path towards building a more secure browser *if it so chose*. You can't build a more secure future by hollowing out and destroying all the progress that has been made uptil a certain point. That's not building a better future. That's simply burning down the house because you want to see something entirely different go up in its place. And, that, sadly is what I suspect is the underlying motivation behind Mozilla's recent actions. Its core mission of building a free browser for the open web appears to have been hijacked from within in the service of making something which is less user friendly, less customisable and overall less fun to use. Mozilla's actions have the net effect of providing succour to its competitors who can breathe a sigh of relief watching Firefox go down of its own accord. I'm still using the "new" Firefox Quantum ESR release to write this blog post, but I doubt for how much longer I will continue to be a Firefox user. Given Mozilla's recent actions it is inevitable that some intrepid groups of coders will decide to develop an alternate Firefox branch, which is not only more secure than Chrome but also does not sacrifice on the essential ability of add-ons developers to customize most aspects of the browser's functionality. Ultimately, the security of any platform does not lie in the hands of its makers, but of its end users. Sure, there will always be those less informed, reckless users who are willing to install clearly malicious add-ons and extensions which allow them to access certain sites or perform other actions which are outside the boundaries of ethical online behavior. However, the entire community should not be penalized for the stupidity of a small group. Doing so, only ensures the rise of a new community built around the enduring notions of freedom of speech and expression, which in a browser context, are represented by the freedom to develop, modify and customize the browsing experience without artificial limitations and restrictions.