---
title: "Thermal Time and Kepler&#039;s Second Law"
date: "2013-02-11"
categories: []
slug: "thermal-time-and-keplers-second-law"
---
In a fascinating recent paper ([arXiv:1302.0724](http://arxiv.org/abs/1302.0724){target="_blank" rel="noopener"}), Haggard and Rovelli (HR) discuss the relationship between the concept of *thermal time*, the Tolman-Ehrenfest effect and the rate of dynamical evolution of a system - *i.e.*, the number of distinguishable (orthogonal) states a given system transitions through in each unit of time. The last of these is also the subject of the Margolus-Levitin theorem ([arXiv:quant-ph/9710043v2](http://arxiv.org/abs/quant-ph/9710043v2){target="_blank" rel="noopener"}) according to which the rate of dynamical evolution of a macroscopic system with fixed average energy (E), has an *upper bound* ($\nu_{\perp}$) given by: 

$$\label{eqn:margolus-levitin} \nu_{\perp} \leq \frac{2E}{h} \\$<!--more-->
Note that$\nu_{\perp}$is the maximum possible rate of dynamical evolution, not the <em>average</em> or <em>mean </em>rate, and also that in [ref{eqn:margolus-levitin}] the bound is determined by the <em>average energy</em>:$E = \sum_n c_n E_n \ket{\psi_n}$of a system in a state$\ket{\Psi} = \sum_n c_n \ket{\psi_n}$, where$\\\\{\ket{\psi_n}\\\\}$is a basis of energy eigenstates of the given system. Therefore, the <em>minimum</em> time step of the system is given by$t^{ML}_{\perp} = h/2E$.
What HR work with is not the average energy of the system, but the fluctuation around the mean given by:$\label{eqn:e-fluctuation} \Delta E^2 = \expect{ H^2 } - \expect{ H } ^2 \\$where$H$is the Hamiltonian of the given system. Thus the elementary time-step that HR consider is given by$t^{HR}_{\perp} = h/2\Delta E$. Now there is a big difference between the two time-steps$t^{HR}_{\perp}$and$t^{ML}_{\perp}$. The former depends on the standard deviation in the mean energy of a given system, while the latter depends on the mean energy itself. The difference can be seen via the following argument given on pg. 8 of ML's paper, and I quote.
<blockquote>For an isolated, macroscopic system with energy average energy$E$, one can construct a state which evolves at a rate$v=2E/h$. If we have several non-interacting macroscopic subsystems, each with average energy$E_i$, then the average energy of the combined system is$E_{tot} = \sum_i E_i$... our construction applies perfectly well to this combination of non-interacting subsystems for which we can construct a state which evolves at a rate$v_{\perp} = 2E_{tot}/h = \sum_i 2E_i/h = \sum_i v^i_{\perp}$. Thus if we subdivide our total energy between separate subsystems, the maximum number of orthogonal states per unit time for the combined system is just the sum of the maximum number for each subsystem taken separately.</blockquote>
Therefore for a composite system, consisting of a number of non-interacting subsystems each with maximum rate of evolution$\nu^{ML}_i$, the maximum rate of evolution is simply the sum of the rates of the individual subsystems:$\nu^{ML} = \sum_i \nu^{ML}_i$. Now, while there is no restriction on the average energy of each of the subsystem, the same is not true for the variance of the energy of each subsystem. In fact, if each of the subsystems is in equilibrium with all the other subsystems and with the composite system as a whole, then the variance of the energy for each subsystem is the same and equal to that of the composite system. Thus, whereas, Margolus-Levitin tell us that increasing the energy of a system increases the (maximum) rate of dynamical evolution, the rate given by Haggard-Rovelli depends only on the temperature$kT \sim \Delta E$, a quantity which does not depend on system size (in a suitable thermodynamic limit). Of course, Haggard-Rovelli do take due care to state that their elementary time-step is the <em>average</em><em> time the system takes to move from one state to the next</em>, so, after all, there is no conflict between their result and the Margolus-Levitin theorem.
<h2>Kepler's Second Law</h2>
Having gone over the distinction between the Margolus-Levitin theorem and the Haggard-Rovelli result, let us move to consider how one can possibly apply Haggard and Rovelli's reasoning to a real world problem, namely that of two-body central force problem in the Newtonian theory of gravitation. There we have <a href="http://en.wikipedia.org/wiki/Kepler%27s_laws_of_planetary_motion" target="_blank" rel="noopener">Kepler's three laws</a>, deduced empirically, which preceded Newton's analytic solution of the two-body problem. The three laws are:
<blockquote>
<ol>
 	<li>The orbit of every planet is an ellipse with the Sun at one of the two foci.</li>
 	<li>A line joining a planet and the Sun sweeps out equal areas during equal intervals of time.</li>
 	<li>The square of the orbital period of a planet is directly proportional to the cube of the semi-major axis of its orbit.</li>
</ol>
</blockquote>
For the time being, let us assume that the two-body Sun+Planet system is a thermal system which happens to be at equilibrium and whose dynamical evolution is given by the motion of the planet around the Sun (or more precisely, the motion of the planet and the sun around <em>each other</em>). Now, according to HR the number of states swept out by such a system in the course of its evolution, over a given interval of time$\delta t$is the same regardless of the location of the system along its dynamic trajector. This is a quantity which depends only on the characteristic temperature$kT$of the system.
For the two-body Sun+Planet system, the "states" in question correspond to the various microscopic configurations of quantum geometry which the system traverses over a given time interval$\delta t_1$. The macroscopic area value$\delta A_1$swept out by the planet's trajectory during$\delta t_1$is a sum over all the microscopic quantum geometric area elements which make up the patch under consideration.$\delta A_1$is thus a measure of the total number of microscopic states the system passes through during$\delta t_1$. Consequently, Haggard-Rovelli tell us that the number of such states the system passes through per unit time is a constant:$\label{eqn:kepler-two} \frac{\delta A}{\delta t} \propto kT \\$$

 **which is nothing other than Kepler's second law of planetary motion**. Thus Haggard and Rovelli's results, along with our understanding of the nature of the microscopic degrees of freedom of quantum geometry allows us to derive one of the most basic results of Newtonian physics - Kepler's second law - and relate it to the thermodynamics of the many-body system consisting of the quantum geometric degrees of freedom which determine the macroscopic orbit of the sun-planet system! Update: July 5, 2016, blog post converted to article and posted to arXiv: Thermal Time and Kepler's Second Law