---
title: "Cosmological Curvature and the Planck Scale"
date: "2019-01-30"
categories: []
slug: "cosmological-curvature-and-the-planck-scale"
---
While reading up on anti-deSitter spaces in [@Bengtsson2008Anti-De], I encountered the following quote attributed to Gauss by the author:

> "I have sometimes in jest expressed the wish that Euclidean geometry is not true. For then we would have an absolute a priori unit of measurement."

This is not just an empty wish. If quantum gravity has anything to say about the situation then Gauss might just be right. The way this can happen is as follows.

# Maximally Symmetric Spacetimes

Flat spacetime, such as the familiar Euclidean space $\mbb{R}^3$or the Minkowski spacetime$\mbb{R}^{3,1}$, is scale invariant, *i.e.* applying the following transformation to all points in the space: $x^\mu \rightarrow \lambda x^\mu$leaves the space(time) invariant. In the absence of some matter fields which provide a length scale, there is no way to establish an absolute unit of measurement in a flat spacetime. However, this no longer holds true in curved space. The simplest examples of curved space are the sphere and the hyperboloid in$n$dimensions. Both are surfaces of *constant curvature*, with the sphere having positive curvature and the hyperboloid having negative curvature. The generalizations of these spaces [@Moschella2005The-de-Sitter; @Gibbons2011Anti-de-Sitter; @Sokolowski2016The-Bizarre] to space-*times* leads us to the deSitter (dS) anti-deSitter (AdS) spacetimes, which correspond to cosmologies with a positive and negative cosmological constant$\Lambda$, respectively. All of these space(times) are *maximally symmetric*, which is a fancy way of saying that if one stands at any point in such a space(time) then the local geometry in all directions appears exactly the same as it would from any other point. A consequence of this is that rather than a complicated object with multiple indices called a "tensor", a single number $R$suffices to characterizes the curvature of these geometries. The meaning of this number can be understood by considering the example of a circle of radius$r$. This is the simplest space with non-zero curvature. The curvature $R$^[1](#fn-942-Symbology)^ of a circle is inversely proportional to its radius:$R = \frac{1}{r}$An observer living of the circle would think that the circle was a "flat" line as long that observer only made measurements in a small neighborhood. The fact that the line is actually a curved circle would only become apparent when the observer made measurements on scales of the order of the circle's radius$r$rather than only in their own neighborhood. This is also what happens to observers living on the Earth's surface. However, the Earth's surface is two-dimensional and for$d > 1$the curvature is inversely proportional to$r^2$rather than to$r$^[2](#fn-942-Radius-Curv-Relation)^. Sailors recognized long ago that the Earth's surface was not flat and they did so because the navigated across the oceans across distances reaching the scale of the square root of the Earth's radius which comes to approximately 80 kilometers ^[3](#fn-942-Scales)^. However, for those who never ventured out beyond their town or county, their would be no reason whatsoever for believing that the Earth's surface was anything but perfectly flat - albeit with the occasional valley or mountain here and there.

# Gaussian Curvature and Length Scale

This is what brings us to Gauss' wish regarding the existence of an absolute unit of measurement. Any *curved*, maximally symmetric spacetime is described by a single number $R$which can be either positive or negative (but not zero). Such a spacetime is *not* invariant under the scale transformations of the former mentioned above and observers in this spacetime will be able to determine the value of$R$by making measurements on large enough scales. This number$R$, would then play the role of an absolute unit of measurement, since one can associate a distance: $r = \frac{1}{\sqrt{R}}$by taking the inverse of the square root of the curvature. What does all this have to do with the Planck scale? Well, theories of quantum gravity such as String Theory and Loop Quantum Gravity (LQG) generically predict that spacetime in not infinitely smooth and that if we zoom in to small enough scales we will find that the smoothness gives way to a discrete, foamy structure, in much the same way that zooming in on the surface of water would eventually cause the smooth appearance of water to break down as we approached a scale where the size of water molecules becomes significant. In other words, there is some absolute *minimum* length scale, usually written as$l_P$- where the subscript$P$stands for "Planck", and called the "[Planck scale](https://www.quantumofgravity.com/blog/2018/10/30/the-planck-scale-may-be-closer-than-it-appears/){rel="noopener" target="_blank"}". From the discussion above we can conclude that if there is such a minimum length scale then it *must* correspond to a macroscopic geometric curvature of the order:$R_{cosmic} \sim l_P^{-2}$ This is a very interesting result because it implies that there is a connection between physics at the smallest possible scales (the Planck scale) and physics at cosmological scales.

# Cosmological Constant and Planck's Constant

One number which characterizes physics on the largest scales is known as the "cosmological constant" [@Carroll2000The-Cosmological] denoted by the capital Greek letter $\Lambda$. It arises as a term which can be added to the Einstein-Hilbert action: $S_{EH+\Lambda} = \frac{1}{2\kappa} \int d^4 x \\, \sqrt{-g} \left( R - 2\Lambda + 2 \kappa \mc{L}<em>M \right)$where$\kappa = 8\pi G_N/c^2$; $g$is the determinant of the four dimensional metric$g \equiv \text{det}(g</em>{\mu\nu})$; $R$is the Ricci curvature of the spacetime and$\Lambda$is the cosmological constant.$\mc{L}<em>M$is the Lagrangian for any matter degrees of freedom. Performing the variation of this action with respect to the metric degree of freedom we obtain the Einstein equations with a cosmological term:$G</em>{\mu\nu} = \frac{8 \pi G_N}{c^2} T_{\mu\nu} - \Lambda g_{\mu\nu} = \kappa \left( T_{\mu\nu} - \frac{1}{\kappa}\Lambda g_{\mu\nu} \right)$Now, the stress-energy tensor$T_{\mu\nu}$is exactly that - a quantity which measures the energy densities due to matter and also due to internal forces at a given point. Energy density has units of$[L]^{-4}$and the Einstein curvature tensor$G_{\mu\nu}$has units$[L]^{-2}$. Therefore the dimensions of $\kappa$must be$[L]^2$. $\Lambda$has units of$[L]^{-2}$. Thus, dividing $\Lambda$by$\kappa$we obtain a quantity which has the same units as the stress-energy tensor and can be interpreted as a contribution$\rho_\Lambda$to the net energy density:$\rho_\Lambda = \frac{1}{\kappa} \Lambda$ In the absence of any other forms of matter ($T_{\mu\nu} = 0$), the cosmological constant alone determines the curvature $G_{\mu\nu}$and hence the large scale curvature of a spacetime. For a maximally symmetric spacetime the various components of the curvature tensor$G_{\mu\nu}$either vanish or become equal to a single number - the Ricci curvature$R$. Einstein's equation then tells us that this curvature is determined by the value of $\Lambda$: $R_{\Lambda} \sim \Lambda$But, from our previous discussion we know that if we think of geometry as being assembled from microscopic pieces of characteristic size$l_p$, where $l_p$is the minimum possible length, then the expected curvature of spacetime will be:$R_{cosmic} \sim l_p^{-2}$Assuming that both these curvatures,$R_\Lambda$and$R_{cosmic}$can be equated, we find that the value of the cosmological constant can be related to the value of the Planck length:$\Lambda \sim l_p^{-2} \sim  10^{68}~m^2$Of course, as is well known the observed value of the cosmological constant is much smaller than the expected value given above. One reason for this discrepancy might be that we have [simply overestimated](https://www.quantumofgravity.com/blog/2018/10/30/the-planck-scale-may-be-closer-than-it-appears/){rel="noopener" target="_blank"} the smallness of the Planck scale. If in fact, the Planck scale is much larger than the naive value of$10^{-34}~m^2$due to the fact that the constants used to define the Planck length -$G$, $c$and$h$- are also scale-dependent, then clearly the discrepancy between the expected value of the cosmological constant and the observed value given by:$\frac{\Lambda^0_{exp}}{\Lambda_{obs}} \sim 10^{-52}$would reduce substantially. Here$\Lambda^0_{exp}$is the expected value of the cosmological constant obtained by using the naive value of the Planck energy$10^{16}$TeV. If instead we use the value for the Planck scale of$\sim 1$TeV, obtained by taking into account the scale dependence of the fundamental constants, then the discrepancy above reduces to a somewhat more manageable level:$\frac{\Lambda_{exp}}{\Lambda_{obs}} \sim 10^{-20}$ Of course, we still need to explain why this ratio is so small. The resolution may well lie in the emergent gravity scenario advocated by Volovik, Padmanabhan and Verlinde [@Padmanabhan2012Emergent; @Verlinde2011On-the-Origin; @Volovik2008Emergent] among others.

------------------------------------------------------------------------

1.  [Why use the symbol $R$for the curvature and$r$for the radius? Since these two quantities are inversely proportional to each other would it not be better to use say$\kappa$for the curvature (as is the [custom](https://en.wikipedia.org/wiki/Curvature) in discussions of Gaussian curvature)? The reason for this, as in most other such notational conundrums in Physics, is historical. For an arbitrary geometry the curvature is defined not by a single number, but by a complicated object with several indices called the Riemann tensor, so-named after Bernhard Riemann, who was Gauss' most gifted student. Naturally the symbol used for the Riemann tensor is \...$R_{\mu\nu\alpha\beta}$, where the indices run from 0 to 3. In the event that the spacetime is maximally symmetric the tensor collapses to a single number which is also called \... $R$. Even for a non-symmetric spacetime, one can construct a single number representing the curvature at any given spacetime point by *contracting* the indices of the Riemann tensor: $R = g^{\mu\alpha} g^{\nu\beta} R_{\mu\nu\alpha\beta}$This quantity was studied by a man named [Gregorio Ricci-Curbastro](http://Gregorio%20Ricci-Curbastro){rel="noopener" target="_blank"} in a paper which he curiously signed with the name Gregorio Ricci. Consequently *this*$R$came to be known as the Ricci scalar and in the case of maximally symmetric spacetime the Ricci scalar is identical to the Gaussian curvature. Thus, any way you look at it, it is difficult to escape using the letter$R$ for the curvature of a maximally symmetric spacetime! ]{#fn-942-Symbology}
2.  [The relation between the radius of curvature $r$and the curvature$R$depends on the dimensionality of the spacetime under consideration. For a one-dimensional geometry, such as that of a circle, the above relation:$R = 1/r$holds. However, for arbitrary dimension$d > 1$, it must be modified to: $R = \frac{1}{r^2}$This can be seen as follows. The metric is a dimensionless quantity. Therefore the Christoffel symbol$\Gamma^\mu_{\alpha\beta}$which depends on first derivatives of the metric has units of$[L]^{-1}$. The Riemann tensor depends on first derivatives of the Christoffel symbol and therefore has units of $[L]^{-2}$. Thus, in general, if we wish to obtain a characteristic length scale given the curvature of a given geometry we must use the relation: $r \sim \frac{1}{\sqrt{R}}$  ]{#fn-942-Radius-Curv-Relation}
3.  [One does not need to navigate across a distance of 80 kilometers in order to be able to infer that the Earth's surface is curved. It is sufficient, for instance to observe the sails of ships vanish over the horizon when seen from a high vantage point such as a lighthouse or a mountaintop, in order to convince ourselves that the surface on which the ships are moving is not flat. The discussion above is only intended to give the reader a general sense of the distance scales involved. ]{#fn-942-Scales}