---
title: "This Year-ish in Theoretical Physics"
date: "2019-12-31"
categories: []
slug: "this-year-ish-in-theoretical-physics"
---
The previous episode of "this week-ish" was posted on June 5. Its been six months since then. I guess its time to post another volume but to be fair the title of this post has been changed to reflect the longer time span its contents refer to.

# Gravity as Quantum Computation (contd from Vol. 1)

In the previous episode of "this week-ish" I [wrote about](https://www.quantumofgravity.com/blog/2019/06/05/this-week-ish-in-theoretical-physics/#Quantum_Computation_as_Gravity) the emerging relationship between quantum computation and quantum gravity, especially with regards to a recent paper by Caputa and Magan [@Caputa2019Quantum]. A recent paper [@Camargo2019Path] has approached this problem from a slightly different perspective. In [@Caputa2019Quantum] and related works the method pioneered by Nielsen is used to argue that *gravity sets the rules for optimal quantum computation*. I will elaborate on the idea behind these approaches in another post. Taken together all these works add greater weight to what I like to call the *computational universe hypothesis* - the premise that all physical phenomena can be viewed as computational processes and that moreover the particle content of our Universe is precisely such that it provides the minimum number of elementary gates needed for universal quantum computation. More on this in a later post.

# Quantum Channels as Thermal Engines

Bringing quantum information *still closer* to statistical mechanics and thermodynamics comes this exciting paper [@Faist2019Thermodynamic] which suggests that one should view quantum channels - essentially operators which map one quantum system into another - as thermodynamic objects with which one can associate a unique quantity called the *thermodynamic capacity*. The physical interpretation of this quantity is, I quote: "the work required to simulate many repetitions of a quantum process employing many repetitions of another quantum process becomes equal to the difference of the respective thermodynamic capacities."

# Experimental Evidence for Lorentz Violation

This [@Huang2019Consistent] is probably one of the most exciting experimental results in recent memory. Lorentz invariance is one of the sacred cornerstones of modern theoretical physics and theories such as loop quantum gravity have often been shrugged off because of the (misguided) belief that discrete quantum geometry is not compatible with microscopic Lorentz invariance. Such beliefs were only strengthened by the negative results of searches for Lorentz violation using the Fermi space telescope [@Nemiroff2012Bounds]. It is therefore very gratifying to see published works which point out that (possible) Lorentz violation has *already* been see by the neutrino observatory known as IceCube. Unverified reports suggest that on finding traces of Lorentz violation the IceCube scientists were heard to yell out "it was a good day!"

# Loops '19: Fun with Kac-Moody algebras and quantum error correction

And, finally, we come to what was without a doubt the most exciting event of 2019. Loops' 19 - the biannual meeting where loop quantum gravity people from all over the globe gather together to plot the overthrow of string theory (muahahahaha) - was held at Penn State. Surprisingly enough my abstract was selected for a parallel talk. Even *more* surprising was the fact that I managed to make it there at all given the bureaucratic maze called "life" here in India, which I had to navigate through! It was my first time attending Loops, which made especially wonderful by the fact that Penn State is where I did my PhD. And, no, it was NOT with Abhay as my advisor if you must ask! My talk was on recent work I have done relating quantum error correction to diffeomorphism invariance of spin networks. Essentially my claim is that LQG naturally incorporates quantum error correcting codes in the form of "noiseless subsystems" [@Zanardi1997Noiseless; @Kribs2005Geometry; @Kribs2005Unified] which, conveniently enough can also be viewed as elementary particles [@Bilson-Thompson2005A-Topological; @Bilson-Thompson2006Quantum; @Hackett2011Invariants; @Hackett2011bInvariants; @Wan2007On-Braid; @Wan2009Effective; @Vaid2010Embedding; @Vaid2013Elementary]. As chance would have it Laurent Freidel presented his most recent work (with Daniele Pranzetti and Etera Livine) [@Freidel2019Gravitational] in an earlier parallel talk. I did have the chance to point out that their idea of replacing spin network edges with tubes was not exactly new and that several other researchers, including me, had suggested the same picture long before their own work. Apparently they were not in the mood to humour my claims of precendence. The response *is* understandable. As a leading LQG researcher recently pointedly mentioned: "[my] papers are unpublished and almost uncited" and moreover, referring to one of my papers,"[it] is rather messy, mixing well-known physics (Hall effect) with original ideas and known ideas (and even almost wrong ideas), all on equal footing." Given this prior feedback I was not surprised by the lack of a response. But, I digress. What matters is that, after much procrastinating, I have finally put my ideas down in another - hopefully not so "messy" - paper [@Vaid2019Quantum]. I cannot be held guilty of being either a great fan of, or even being very capable of, mathematical rigor. Thus, those looking for page upon page of math will be disappointed. The physical picture is, however, I believe very clear. I would love to hear more from anybody who does find the time to look through my work. That's all folks. Wishing you all a very happy new year. I leave you with some wonderful memories from Loops' 19.

*Image gallery omitted from the static migration.*